SRC = $(wildcard *.cpp gl/*.cpp renderer/*.cpp lodepng/*.cpp)
# the object tree mirrors the source tree: ocean.cpp and renderer/ocean.cpp are two
# different files and $(notdir) would map them onto the same .o
OBJ = $(addprefix build/, $(SRC:.cpp=.o))
DEP = $(addprefix build/, $(SRC:.cpp=.d))
CXXFLAGS=-I. -g -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter

all: p3d_gl.a

-include $(DEP)

p3d_gl.a: $(OBJ)
	ar rcs $@ $^

build/%.o: %.cpp
	@mkdir -p $(dir $@)
	c++ -MMD $(CXXFLAGS) -c $< -o $@
