"""Dump every demangled class name in the PS2 ELF together with its RTTI
record, its base classes and the vtable(s) that point at the RTTI record.

Layout found in SLES_541.82 (see re/notes/ps2.md):

    <string>              "renderer::WorldGeoRenderable\0"   (16-byte aligned)
    <bases>               { TypeInfo* base; u32 pad; } ... , terminated by 0
    <TypeInfo>            { const char* name; TypeInfo** bases; }
    ...
    <vtable>              { TypeInfo* rtti; u32 zero; void* method[N]; }
                          an object's vptr points at the rtti word, so
                          method k lives at vptr + 8 + 4*k.

usage: re/venv/bin/python re/ps2/classnames.py > re/ps2/classnames.txt
"""
import re, struct, sys, os, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ps2elf


def main():
    img = ps2elf.Image()
    refs, consts, jals = ps2elf.scan(img)

    # index of every 4-aligned word -> addresses holding it
    wordidx = collections.defaultdict(list)
    for vaddr, filesz, off in img.segs:
        n = filesz // 4
        for k, v in enumerate(struct.unpack_from('<%dI' % n, img.data, off)):
            if 0x100000 <= v < 0x850000:
                wordidx[v].append(vaddr + 4*k)

    pat = re.compile(rb'[A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_:<>, ]*)+\x00')
    byti = {}
    entries = []
    for m in pat.finditer(img.data):
        sva = img.va_of_off(m.start())
        if sva is None or m.start() % 4:
            continue
        name = m.group()[:-1].decode('latin1')
        # the TypeInfo record is the word that points at the string and whose
        # following word points at a bases list (or is 0)
        tis = [a for a in wordidx.get(sva, [])
               if img.u32(a+4) is not None and (img.u32(a+4) == 0 or img.seg_of(img.u32(a+4)))]
        for ti in tis:
            byti[ti] = name
        entries.append((sva, name, tis))

    print('# class name table of SLES_541.82 (Scarface PS2)')
    print('# generated by re/ps2/classnames.py; see re/notes/ps2.md')
    print('# str=<class-name string>  ti=<TypeInfo {name,bases}>  vt=<vtable, vptr value>')
    print('# "bases" is the TypeInfo base list, "xref" are code sites (lui/addiu)')
    print('# that build the address of the string or of the TypeInfo record.')
    print('# %d class names' % len(entries))
    for sva, name, tis in entries:
        vts = []
        bases = []
        xref = list(refs.get(sva, []))
        for ti in tis:
            xref += refs.get(ti, [])
            b = img.u32(ti+4)
            if b and img.seg_of(b):
                k = b
                while True:
                    p = img.u32(k)
                    if not p:
                        break
                    bases.append(byti.get(p, '?%08x' % p))
                    k += 8
            for a in wordidx.get(ti, []):
                m0 = img.u32(a+8)
                if img.u32(a+4) == 0 and m0 and 0x1a0000 <= m0 < 0x7a0000:
                    vts.append(a)
        print('%08x ti=%s vt=%s %s' % (
            sva,
            ','.join('%08x' % t for t in tis) or '-',
            ','.join('%08x' % v for v in vts) or '-',
            name))
        if bases:
            print('         bases %s' % ' '.join(bases))
        if xref:
            print('         xref %s' % ' '.join('%08x' % a for a in sorted(set(xref))))


if __name__ == '__main__':
    main()
