# conflict 00461870: renderer::RenderableHandle::RenderableHandle (names/rendercore.txt) vs renderer::RenderableHandle::ctor (notes/instances.md) -> keeping first
# conflict 0046f8e0: renderer::InstanceRenderable::InstanceRenderable (names/renderable_classes.txt) vs renderer::InstanceRenderable::ctor (notes/instances.md) -> keeping first
# conflict 0046f250: renderer::InstanceRenderable::~InstanceRenderable (names/renderable_classes.txt) vs renderer::InstanceRenderable::dtor (notes/instances.md) -> keeping first
# conflict 0046f840: renderer::InstanceContainer::InstanceContainer (names/renderable_classes.txt) vs renderer::InstanceContainer::ctor (notes/instances.md) -> keeping first
# conflict 0046f2e0: renderer::InstancePrimitive::InstancePrimitive (names/renderable_classes.txt) vs renderer::InstancePrimitive::ctor (notes/instances.md) -> keeping first
# conflict 00473fc0: renderer::Renderable::GetElementDrawable (names/rendercore.txt) vs renderer::Renderable::GetElement (notes/instances.md) -> keeping first
# conflict 008111c8: renderer::g_renderAllocator (names/rendercore.txt) vs MemoryAllocator (notes/rendercore.md) -> keeping first
# conflict 00458f00: renderer::DisplayListPrimitive::Display (notes/displaylist.md) replaced by renderer::DisplayListPrimitive::SetVisible (notes/renderspine.md)
# conflict 00464d00: renderer::View_SetCullingCamera (names/rendercore.txt) vs renderer::SetCurrentCamera (notes/renderspine.md) -> keeping first
# conflict 00460900: occlude::Occluder_TestSphere (names/rendercore.txt) vs occlude::Occluder::TestSphere (notes/renderspine.md) -> keeping first
# generated by re/mkidanames.py — 544 names; run in IDA: File > Script file
import idc, idaapi
def n(ea, name):
    if not idc.set_name(ea, name, idc.SN_NOWARN | idc.SN_FORCE):
        print("failed: %x %s" % (ea, name))
n(0x0042a180, 'the_StatePropManager')  # notes/instances.md
n(0x00438400, 'pure3d::Entity::SetName_stub')  # names/rendercore.txt
n(0x00441a40, 'GameGroup::ctor')  # notes/instances.md
n(0x004453d0, 'ScriptObject::SetProperty')  # notes/instances.md
n(0x00458210, 'renderer::Canvas::Canvas')  # names/rendercore.txt
n(0x004582e0, 'renderer::Canvas::SetBackgroundColour')  # names/rendercore.txt
n(0x00458300, 'renderer::Canvas::SetFog')  # names/rendercore.txt
n(0x00458390, 'renderer::Canvas::UpdateFog')  # names/rendercore.txt
n(0x00458620, 'renderer::Canvas::RenderScene')  # notes/renderspine.md
n(0x00458640, 'renderer::Canvas::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x004589d0, 'renderer::SetGlobalDisplayList')  # notes/displaylist.md
n(0x004589e0, 'renderer::Display_List::CmpKey')  # names/displaylist.txt
n(0x00458a20, 'renderer::Display_List::RemovePrimitiveNodes')  # notes/renderspine.md
n(0x00458ba0, 'occlude::Occluder::TestBox')  # names/displaylist.txt
n(0x00458bf0, 'occlude::IsBoxVisible')  # names/displaylist.txt
n(0x00458c60, 'renderer::DisplayListPrimitive::DisplayListPrimitive')  # notes/displaylist.md
n(0x00458cc0, 'renderer::DisplayListPrimitive::~DisplayListPrimitive')  # notes/displaylist.md
n(0x00458d30, 'renderer::DisplayListPrimitive::DisplayListPrimitive_copy')  # notes/displaylist.md
n(0x00458e50, 'renderer::DisplayListPrimitive::SetDrawable')  # notes/displaylist.md
n(0x00458ea0, 'renderer::DisplayListPrimitive::RemoveFromList')  # notes/renderspine.md
n(0x00458ec0, 'renderer::DisplayListPrimitive::SetVisible')  # notes/displaylist.md
n(0x00458f00, 'renderer::DisplayListPrimitive::SetVisible')  # notes/renderspine.md
n(0x00458ff0, 'renderer::Display_List::CmpKeyThenDepth')  # names/displaylist.txt
n(0x00459060, 'renderer::Display_List::CmpShader')  # names/displaylist.txt
n(0x00459090, 'renderer::Display_List::CmpKeyThenMaterial')  # names/displaylist.txt
n(0x00459120, 'renderer::Display_List::ComputeDepthKeys')  # names/displaylist.txt
n(0x004591e0, 'renderer::Display_List::ComputeDepthKeysList66')  # names/displaylist.txt
n(0x00459260, 'renderer::Display_List::SortGroup_30_39_24')  # names/displaylist.txt
n(0x004592c0, 'renderer::Display_List::SortGroup_4_3_18_17_75')  # names/displaylist.txt
n(0x00459350, 'renderer::Display_List::SortGroup_5_6_19_20')  # names/displaylist.txt
n(0x004593c0, 'renderer::Display_List::SortGroup_78_80_79_81')  # names/displaylist.txt
n(0x00459460, 'renderer::Display_List::SortGroup_29_50')  # names/displaylist.txt
n(0x004594b0, 'renderer::Display_List::SortGroup_37_38')  # names/displaylist.txt
n(0x00459500, 'renderer::Display_List::SortGroup_7_8_77')  # names/displaylist.txt
n(0x00459560, 'renderer::Display_List::SortGroup_Buildings')  # names/displaylist.txt
n(0x004596f0, 'renderer::Display_List::SortGroup_52_53_56_55')  # names/displaylist.txt
n(0x00459780, 'renderer::Display_List::SortGroup_36_41_42_45')  # names/displaylist.txt
n(0x00459810, 'renderer::Display_List::RenderCameraLocked76')  # notes/displaylist.md
n(0x00459910, 'renderer::Display_List::RenderList')  # names/displaylist.txt
n(0x00459a00, 'renderer::Display_List::RenderSky')  # notes/displaylist.md
n(0x00459be0, 'renderer::Display_List::RenderDepthOnly58')  # notes/displaylist.md
n(0x00459c80, 'renderer::Display_List::RenderWater65')  # notes/displaylist.md
n(0x00459f70, 'renderer::Display_List::RenderWaterSurface66')  # notes/displaylist.md
n(0x0045a010, 'renderer::Display_List::RenderShadowVolumes_61_63_64')  # notes/displaylist.md
n(0x0045a4c0, 'renderer::Display_List::RenderInstanced72')  # notes/displaylist.md
n(0x0045a620, 'renderer::Display_List::RenderInstanced74')  # notes/displaylist.md
n(0x0045a680, 'renderer::Display_List::RenderInstanced73')  # notes/displaylist.md
n(0x0045a770, 'renderer::Display_List::RenderLightSet82')  # notes/displaylist.md
n(0x0045a7f0, 'renderer::Display_List::RenderLightSet83')  # notes/displaylist.md
n(0x0045a890, 'renderer::Display_List::RenderLightSet69')  # notes/displaylist.md
n(0x0045a910, 'renderer::Display_List::RenderLightSet71')  # notes/displaylist.md
n(0x0045a9b0, 'renderer::Display_List::RenderLightSet70')  # notes/displaylist.md
n(0x0045aa50, 'renderer::Display_List::RenderLightSet67')  # notes/displaylist.md
n(0x0045ab20, 'renderer::Display_List::RenderLightSet68')  # notes/displaylist.md
n(0x0045ac10, 'renderer::Display_List::RenderUnderwater_78_79')  # notes/displaylist.md
n(0x0045ac90, 'renderer::Display_List::RenderUnderwaterFading_80_81')  # notes/displaylist.md
n(0x0045ad10, 'renderer::Display_List::SortAllLists')  # names/displaylist.txt
n(0x0045b0c0, 'renderer::Display_List::FreeOrphanNodes')  # notes/renderspine.md
n(0x0045b110, 'renderer::Display_List::IsNodeVisible')  # names/displaylist.txt
n(0x0045b240, 'renderer::Display_List::RenderSpecularPass2_15_13')  # notes/displaylist.md
n(0x0045b590, 'renderer::Display_List::RenderDecals_3_17_18_4_75')  # notes/displaylist.md
n(0x0045b870, 'renderer::Display_List::RenderDecalsFading_5_19_20_6')  # notes/displaylist.md
n(0x0045bb90, 'renderer::Display_List::RenderReflection')  # notes/displaylist.md
n(0x0045bce0, 'renderer::Display_List::RenderProjectedShadows62')  # notes/displaylist.md
n(0x0045bf30, 'renderer::Display_List::RenderLit_29_50')  # notes/displaylist.md
n(0x0045c070, 'renderer::Display_List::RenderCbvAlphaTest_26_22')  # notes/displaylist.md
n(0x0045c280, 'renderer::Display_List::RenderCbvDefault23')  # notes/displaylist.md
n(0x0045c3c0, 'renderer::Display_List::RenderUnlit_38_37')  # notes/displaylist.md
n(0x0045c590, 'renderer::Display_List::RenderAdditive_39_30_24')  # notes/displaylist.md
n(0x0045c800, 'renderer::Display_List::RenderOpaqueBuildings_21_27_28_35_43')  # notes/displaylist.md
n(0x0045caf0, 'renderer::Display_List::RenderShadowDecals_7_8_77')  # notes/displaylist.md
n(0x0045ccd0, 'renderer::Display_List::RenderUnlitBlendAndLayered_36_42')  # notes/displaylist.md
n(0x0045ce00, 'renderer::Display_List::RenderFading_41_45')  # notes/displaylist.md
n(0x0045cfb0, 'renderer::Display_List::RenderInteriorFloors_33_34')  # notes/displaylist.md
n(0x0045d140, 'renderer::Display_List::RenderLowLOD59')  # notes/displaylist.md
n(0x0045d1f0, 'renderer::Display_List::RenderVertexFade2')  # notes/displaylist.md
n(0x0045d360, 'renderer::Display_List::AddContainer')  # names/displaylist.txt
n(0x0045d3b0, 'renderer::Display_List::AddContainerElement')  # names/displaylist.txt
n(0x0045d9a0, 'renderer::Display_List::~Display_List')  # notes/displaylist.md
n(0x0045da30, 'renderer::Display_List::RenderCardsNight12')  # notes/displaylist.md
n(0x0045db80, 'renderer::Display_List::RenderNightLights11')  # notes/displaylist.md
n(0x0045dcf0, 'renderer::Display_List::RenderEnv_9_10')  # notes/displaylist.md
n(0x0045deb0, 'renderer::Display_List::RenderSpecular_13_15')  # notes/displaylist.md
n(0x0045e030, 'renderer::Display_List::RenderSpecularFading_14_16')  # notes/displaylist.md
n(0x0045e240, 'renderer::Display_List::RenderFadingBlend_44_25_32_31_40')  # notes/displaylist.md
n(0x0045e680, 'renderer::Display_List::Render')  # names/displaylist.txt
n(0x0045f110, 'renderer::Display_List::Display_List')  # notes/displaylist.md
n(0x0045f370, 'renderer::Display_List::ScalarDeletingDtor')  # names/displaylist.txt
n(0x0045fa50, 'renderer::LightManager::FindRoom')  # names/rendercore.txt
n(0x0045fbd0, 'renderer::LightManager::AddTemplateLight')  # names/rendercore.txt
n(0x0045fc30, 'renderer::LightManager::RemoveTemplateLight')  # names/rendercore.txt
n(0x0045fc50, 'renderer::LightManager::UpdateTemplateLight')  # names/rendercore.txt
n(0x00460130, 'renderer::LightManager::Update')  # names/rendercore.txt
n(0x00460600, 'renderer::LightManager::LightManager')  # names/rendercore.txt
n(0x00460810, 'occlude::Occluder::~Occluder')  # names/rendercore.txt
n(0x00460900, 'occlude::Occluder_TestSphere')  # names/rendercore.txt
n(0x00460980, 'occlude::TestSphere')  # names/rendercore.txt
n(0x00460a50, 'occlude::IsVisible')  # names/rendercore.txt
n(0x00460a90, 'occlude::Occluder::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00461650, 'occlude::OccluderLoader::LoadObject')  # names/rendercore.txt
n(0x00461840, 'occlude::OccluderLoader::OccluderLoader')  # names/rendercore.txt
n(0x00461860, 'renderer::RenderableHandle::RenderableHandle_empty')  # names/rendercore.txt
n(0x00461870, 'renderer::RenderableHandle::RenderableHandle')  # names/rendercore.txt
n(0x004618d0, 'renderer::RenderableHandle::Detach')  # names/rendercore.txt
n(0x00461920, 'renderer::RenderableHandle::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00461980, 'renderer::SkidMarksHandle::SkidMarksHandle')  # names/rendercore.txt
n(0x004619f0, 'renderer::SkidMarksHandle::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00461a10, 'renderer::SkidMarksHandle::~SkidMarksHandle')  # names/rendercore.txt
n(0x00461ac0, 'renderer::View_GetRenderingCamera')  # names/rendercore.txt
n(0x00461ad0, 'renderer::View_GetCullingCamera')  # names/rendercore.txt
n(0x00461d40, 'renderer::IsMainCharacterInInterior')  # names/rendercore.txt
n(0x00461e00, 'renderer::View_SetBackGroundColour')  # names/rendercore.txt
n(0x00461ed0, 'renderer::View_SetFog')  # names/rendercore.txt
n(0x00461f50, 'renderer::View_GetColourEffectsParameters')  # names/rendercore.txt
n(0x00461f70, 'renderer::View_GetFog')  # names/rendercore.txt
n(0x00461fd0, 'renderer::View_EnableDepthOfField')  # names/rendercore.txt
n(0x00462030, 'renderer::View_EnableColourEffects')  # names/rendercore.txt
n(0x00462050, 'renderer::View_IsColorEffectsEnabled')  # names/rendercore.txt
n(0x00462060, 'renderer::View_SetColourEffectsParameters')  # names/rendercore.txt
n(0x00462170, 'renderer::Renderable_SetVisible')  # names/rendercore.txt
n(0x004621d0, 'renderer::Renderable_DisableLOD')  # names/rendercore.txt
n(0x00462340, 'renderer::Renderable_Destroy')  # names/rendercore.txt
n(0x00462370, 'renderer::Renderable_SetTransform')  # names/rendercore.txt
n(0x00463db0, 'renderer::AddInstance')  # notes/instances.md
n(0x00463e60, 'renderer::InstanceRenderable_RemoveInstance')  # notes/instances.md
n(0x00463e80, 'renderer::InstanceRenderable_GetInstanceMatrix')  # notes/instances.md
n(0x00463f80, 'renderer::SetCullDistance')  # names/rendercore.txt
n(0x00464660, 'renderer::RenderManager::SetMainCharacter')  # names/rendercore.txt
n(0x00464690, 'renderer::DecalsHandle::DecalsHandle')  # names/rendercore.txt
n(0x00464720, 'renderer::DecalsHandle::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00464740, 'renderer::DecalsHandle::~DecalsHandle')  # names/rendercore.txt
n(0x004647b0, 'renderer::TraceFireHandle::TraceFireHandle')  # names/rendercore.txt
n(0x00464840, 'renderer::TraceFireHandle::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00464860, 'renderer::TraceFireHandle::~TraceFireHandle')  # names/rendercore.txt
n(0x00464ac0, 'renderer::DestroyPendingRenderables')  # names/rendercore.txt
n(0x00464c80, 'renderer::RenderFlowClient::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00464ca0, 'renderer::View_SetRenderingCamera')  # names/rendercore.txt
n(0x00464d00, 'renderer::View_SetCullingCamera')  # names/rendercore.txt
n(0x00464e00, 'renderer::Scene_Enable')  # names/rendercore.txt
n(0x00464f00, 'renderer::Renderable_CreateInstance')  # names/renderable_classes.txt
n(0x00465120, 'renderer::Init')  # names/rendercore.txt
n(0x00465500, 'renderer::FindGeometryInInventory')  # names/rendercore.txt
n(0x00465520, 'renderer::RenderFlowClient::RenderFlowClient')  # names/rendercore.txt
n(0x00465590, 'renderer::RenderFlowClient::OnFrame')  # names/rendercore.txt
n(0x00465840, 'renderer::ParticleEffectRenderable_Create')  # names/renderable_classes.txt
n(0x00465990, 'renderer::StatePropRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00465c80, 'renderer::DecalRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00465d50, 'renderer::TraceFireRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00465e60, 'renderer::VehicleRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x004661b0, 'renderer::CharacterRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00466310, 'renderer::NISRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x004664a0, 'renderer::ZonePkgRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00466600, 'renderer::PropRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x004667c0, 'renderer::SkyRenderable_Create')  # names/renderable_classes.txt
n(0x00466940, 'renderer::OceanRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00466b10, 'renderer::WakeRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00466ce0, 'renderer::LightingRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00466e90, 'renderer::RainRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x00467060, 'renderer::CreateInstanceRenderable')  # notes/instances.md
n(0x00467210, 'renderer::ShadowRenderable_CreateInstance')  # names/renderable_classes.txt
n(0x004673c0, 'renderer::CreateRenderFlowClient')  # names/rendercore.txt
n(0x004675b0, 'renderer::RenderManager::GetHeap')  # names/rendercore.txt
n(0x004675c0, 'renderer::RenderManager::EnableSky')  # names/rendercore.txt
n(0x004676b0, 'renderer::RenderManager::InitHeapTable')  # names/rendercore.txt
n(0x00467810, 'renderer::RenderManager::Update')  # notes/renderspine.md
n(0x00467950, 'renderer::RenderManager::SetSky')  # names/rendercore.txt
n(0x00467a00, 'renderer::RenderManager::RenderManager')  # names/rendercore.txt
n(0x00468470, 'renderer::RenderManager::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00468490, 'renderer::RenderManager::Init')  # names/rendercore.txt
n(0x004689a0, 'renderer::RenderManager::Render')  # notes/renderspine.md
n(0x00468a70, 'renderer::Scene::EnableTypes')  # names/rendercore.txt
n(0x00468a90, 'renderer::GamePlayScene::SetName')  # names/rendercore.txt
n(0x00468aa0, 'renderer::GamePlayScene::Render')  # names/rendercore.txt
n(0x00468ac0, 'renderer::Scene::AddRenderable')  # names/rendercore.txt
n(0x00468b20, 'renderer::Scene::RemoveRenderable')  # names/rendercore.txt
n(0x00468b80, 'renderer::Scene::Render')  # names/rendercore.txt
n(0x00468c00, 'renderer::Scene::Update')  # names/rendercore.txt
n(0x00468c50, 'renderer::GamePlayScene::Update')  # names/rendercore.txt
n(0x00468cc0, 'renderer::GamePlayScene::AddRenderable')  # names/rendercore.txt
n(0x00468d10, 'renderer::GamePlayScene::RemoveRenderable')  # names/rendercore.txt
n(0x00468d60, 'renderer::Scene::AllocSlots')  # names/rendercore.txt
n(0x00468dd0, 'renderer::Scene::~Scene')  # names/rendercore.txt
n(0x00468e60, 'renderer::GamePlayScene::~GamePlayScene')  # names/rendercore.txt
n(0x00468ed0, 'renderer::Scene::Scene')  # names/rendercore.txt
n(0x00468f70, 'renderer::Scene::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x00468f90, 'renderer::GamePlayScene::GamePlayScene')  # names/rendercore.txt
n(0x00469050, 'renderer::GamePlayScene::__scalar_deleting_dtor')  # names/rendercore.txt
n(0x0046a520, 'renderer::EnvManager::IsCameraIndoors')  # names/rendercore.txt
n(0x0046c5f0, 'renderer::CharacterRenderable::GetPosition')  # names/renderable_classes.txt
n(0x0046c620, 'renderer::CharacterRenderable::Display')  # names/renderable_classes.txt
n(0x0046c650, 'renderer::CharacterRenderable::CharacterRenderable')  # names/renderable_classes.txt
n(0x0046c8f0, 'renderer::CharacterRenderable::Update')  # names/renderable_classes.txt
n(0x0046ca60, 'renderer::CharacterRenderable::~CharacterRenderable')  # names/renderable_classes.txt
n(0x0046ca80, 'renderer::CharacterLoader::CharacterLoader')  # names/renderable_classes.txt
n(0x0046cad0, 'renderer::CharacterLoader::LoadObject')  # names/renderable_classes.txt
n(0x0046ce10, 'renderer::DecalPrimitive::Decal_dtor')  # names/renderable_classes.txt
n(0x0046ced0, 'renderer::DecalPrimitive::Update')  # names/renderable_classes.txt
n(0x0046d040, 'renderer::DecalPrimitive::RemoveDecal')  # names/renderable_classes.txt
n(0x0046d110, 'renderer::DecalPrimitive::GetTypeMask')  # names/renderable_classes.txt
n(0x0046d150, 'renderer::Renderable::RenderImmediate_viaContainer')  # names/renderable_classes.txt
n(0x0046d1d0, 'renderer::DecalPrimitive::Decal_ctor')  # names/renderable_classes.txt
n(0x0046d3a0, 'renderer::DecalPrimitive::CDecalDrawable::CDecalDrawable')  # names/renderable_classes.txt
n(0x0046d3c0, 'renderer::DecalPrimitive::CStaticDecalDrawable::CStaticDecalDrawable')  # names/renderable_classes.txt
n(0x0046d4e0, 'renderer::DecalPrimitive::COceanDecalDrawable::COceanDecalDrawable')  # names/renderable_classes.txt
n(0x0046d780, 'renderer::DecalPrimitive::DecalPrimitive')  # names/renderable_classes.txt
n(0x0046d840, 'renderer::DecalPrimitive::~DecalPrimitive')  # names/renderable_classes.txt
n(0x0046d860, 'renderer::DecalPrimitive::Display')  # names/renderable_classes.txt
n(0x0046dbf0, 'renderer::DecalContainer::~DecalContainer')  # names/renderable_classes.txt
n(0x0046dc10, 'renderer::DecalRenderable::~DecalRenderable')  # names/renderable_classes.txt
n(0x0046dd70, 'renderer::DecalPrimitive::CDecalDrawable::~CDecalDrawable')  # names/renderable_classes.txt
n(0x0046ddb0, 'renderer::DecalPrimitive::CStaticDecalDrawable::~CStaticDecalDrawable')  # names/renderable_classes.txt
n(0x0046ddd0, 'renderer::DecalPrimitive::COceanDecalDrawable::~COceanDecalDrawable')  # names/renderable_classes.txt
n(0x0046ea70, 'renderer::DecalContainer::DecalContainer')  # names/renderable_classes.txt
n(0x0046eb00, 'renderer::DecalRenderable::DecalRenderable')  # names/renderable_classes.txt
n(0x0046ebb0, 'renderer::DecalRenderable::scalar_deleting_dtor')  # names/renderable_classes.txt
n(0x0046ebd0, 'renderer::DecalRenderable::Update')  # names/renderable_classes.txt
n(0x0046ebe0, 'renderer::DecalRenderable::RemoveDecal')  # names/renderable_classes.txt
n(0x0046ed10, 'renderer::InstancePrimitive::GetTypeMask')  # names/renderable_classes.txt
n(0x0046edc0, 'renderer::InstancePrimitive::ComputeLODBands')  # notes/renderspine.md
n(0x0046f030, 'renderer::InstancePrimitive::PreDisplay')  # notes/renderspine.md
n(0x0046f0f0, 'renderer::InstancePrimitive::DrawInstanced')  # notes/renderspine.md
n(0x0046f110, 'renderer::InstancePrimitive::Display')  # notes/instances.md
n(0x0046f230, 'renderer::InstanceContainer::~InstanceContainer')  # names/renderable_classes.txt
n(0x0046f250, 'renderer::InstanceRenderable::~InstanceRenderable')  # names/renderable_classes.txt
n(0x0046f2e0, 'renderer::InstancePrimitive::InstancePrimitive')  # names/renderable_classes.txt
n(0x0046f490, 'renderer::InstancePrimitive::~InstancePrimitive')  # names/renderable_classes.txt
n(0x0046f4b0, 'renderer::InstancePrimitive::AddInstance')  # notes/instances.md
n(0x0046f840, 'renderer::InstanceContainer::InstanceContainer')  # names/renderable_classes.txt
n(0x0046f8e0, 'renderer::InstanceRenderable::InstanceRenderable')  # names/renderable_classes.txt
n(0x0046f9c0, 'renderer::InstanceRenderable::scalar_deleting_dtor')  # names/renderable_classes.txt
n(0x0046fba0, 'renderer::InstanceRenderable::AddInstance')  # notes/instances.md
n(0x0046fbf0, 'renderer::InstanceRenderable::SetCullDistance')  # names/renderable_classes.txt
n(0x0046fc40, 'renderer::InstanceRenderable::Update')  # names/renderable_classes.txt
n(0x0046ff10, 'renderer::LightingRenderable::LightingRenderable')  # names/renderable_classes.txt
n(0x00470240, 'renderer::LightingRenderable::~LightingRenderable')  # names/renderable_classes.txt
n(0x00470260, 'renderer::SFLightGroupLoader::SFLightGroupLoader')  # names/renderable_classes.txt
n(0x00470280, 'renderer::SFLightGroupLoader::LoadObject')  # names/renderable_classes.txt
n(0x004704a0, 'renderer::MaskRenderable::~MaskRenderable')  # names/renderable_classes.txt
n(0x004704c0, 'renderer::MaskRenderable::MaskRenderable')  # names/renderable_classes.txt
n(0x00470550, 'renderer::NISRenderable::GetPosition')  # names/renderable_classes.txt
n(0x004705b0, 'renderer::NISRenderable::NISRenderable')  # names/renderable_classes.txt
n(0x00470630, 'renderer::NISRenderable::~NISRenderable')  # names/renderable_classes.txt
n(0x00470650, 'renderer::NISRenderable::Update')  # names/renderable_classes.txt
n(0x004707a0, 'renderer::OceanPrimitive::Display')  # names/renderable_classes.txt
n(0x004707b0, 'renderer::OceanPrimitive::GetTypeMask')  # names/renderable_classes.txt
n(0x004707c0, 'renderer::OceanPrimitive::CalcBounds')  # names/renderable_classes.txt
n(0x00470800, 'renderer::OceanContainer::GetTypeMask')  # names/renderable_classes.txt
n(0x00470810, 'renderer::Renderable::Display_thunk')  # names/renderable_classes.txt
n(0x00470820, 'renderer::OceanPrimitive::OceanPrimitive')  # names/renderable_classes.txt
n(0x00470990, 'renderer::OceanContainer::~OceanContainer')  # names/renderable_classes.txt
n(0x00470a20, 'renderer::OceanPrimitive::~OceanPrimitive')  # names/renderable_classes.txt
n(0x00470a40, 'renderer::OceanContainer::OceanContainer')  # names/renderable_classes.txt
n(0x00470ad0, 'renderer::OceanRenderable::OceanRenderable')  # names/renderable_classes.txt
n(0x00470ba0, 'renderer::OceanRenderable::~OceanRenderable')  # names/renderable_classes.txt
n(0x00470be0, 'renderer::OceanRenderable::Update')  # names/renderable_classes.txt
n(0x00470c30, 'renderer::ParticleEffectRenderable::Update')  # names/renderable_classes.txt
n(0x00470d70, 'renderer::ParticleEffectRenderable::ParticleEffectRenderable')  # names/renderable_classes.txt
n(0x00470ec0, 'renderer::ParticleEffectRenderable::~ParticleEffectRenderable')  # names/renderable_classes.txt
n(0x00471250, 'renderer::ParticleEffectRenderable::SetMatrix')  # names/renderable_classes.txt
n(0x004712d0, 'renderer::PlugInRenderable::PlugInRenderable')  # names/renderable_classes.txt
n(0x00471310, 'renderer::PlugInRenderable::RenderImmediate')  # names/renderable_classes.txt
n(0x00471330, 'renderer::PlugInRenderable::Clone')  # names/renderable_classes.txt
n(0x004713c0, 'renderer::PlugInRenderable::~PlugInRenderable')  # names/renderable_classes.txt
n(0x004713e0, 'renderer::PropRenderable::PropRenderable')  # names/renderable_classes.txt
n(0x00471460, 'renderer::PropRenderable::Update')  # names/renderable_classes.txt
n(0x00471490, 'renderer::WorldGeoRenderable::WorldGeoRenderable')  # names/renderable_classes.txt
n(0x004714e0, 'renderer::WorldGeoRenderable::GetDistanceRefPos')  # notes/renderspine.md
n(0x00471510, 'renderer::WorldGeoRenderable::Hide')  # names/renderable_classes.txt
n(0x00471570, 'renderer::WorldGeoRenderable::SetVisible')  # names/renderable_classes.txt
n(0x00471620, 'renderer::PropRenderable::~PropRenderable')  # names/renderable_classes.txt
n(0x00471640, 'renderer::WorldGeoRenderable::Display')  # notes/renderspine.md
n(0x00471bc0, 'renderer::ZonePkgRenderable::SetVisible')  # names/renderable_classes.txt
n(0x00471c10, 'renderer::ZonePkgLoader::ApplyZoneEntry')  # names/renderable_classes.txt
n(0x00471d60, 'renderer::WorldGeoRenderable::~WorldGeoRenderable')  # names/renderable_classes.txt
n(0x00471d80, 'renderer::WorldGeoLoader::WorldGeoLoader')  # names/renderable_classes.txt
n(0x00471e50, 'renderer::ZonePkgLoader::ZonePkgLoader')  # names/renderable_classes.txt
n(0x00471e70, 'renderer::ZonePkgRenderable::~ZonePkgRenderable')  # names/renderable_classes.txt
n(0x00471ec0, 'renderer::WorldGeoLoader::LoadObject')  # names/renderable_classes.txt
n(0x00472680, 'renderer::ZonePkgLoader::LoadObject')  # names/renderable_classes.txt
n(0x00472af0, 'renderer::RainRenderable::RenderImmediate')  # names/renderable_classes.txt
n(0x004732c0, 'renderer::RainRenderable::RainRenderable')  # names/renderable_classes.txt
n(0x004734e0, 'renderer::RainRenderable::~RainRenderable')  # names/renderable_classes.txt
n(0x00473940, 'renderer::RainRenderable::Update')  # names/renderable_classes.txt
n(0x00473aa0, 'renderer::Renderable::SetToFadeIn')  # names/rendercore.txt
n(0x00473ac0, 'renderer::Renderable::SetToFadeOut')  # names/rendercore.txt
n(0x00473ae0, 'renderer::Renderable::FadeInTo')  # names/rendercore.txt
n(0x00473b10, 'renderer::Renderable::FadeOutTo')  # names/rendercore.txt
n(0x00473b40, 'renderer::Renderable::SetMatrix')  # names/rendercore.txt
n(0x00473b60, 'renderer::Renderable::~Renderable_body')  # names/rendercore.txt
n(0x00473b70, 'renderer::Renderable::Reset')  # names/rendercore.txt
n(0x00473c00, 'renderer::Renderable::GetPosition')  # names/rendercore.txt
n(0x00473c20, 'renderer::Renderable::SetVisible')  # names/rendercore.txt
n(0x00473c80, 'renderer::Renderable::Hide')  # names/rendercore.txt
n(0x00473cc0, 'renderer::Renderable::UpdateRoom')  # names/rendercore.txt
n(0x00473d40, 'renderer::Renderable::SetFade2')  # names/rendercore.txt
n(0x00473d90, 'renderer::Renderable::UpdateFade')  # notes/renderspine.md
n(0x00473e70, 'renderer::Renderable::SetElement')  # names/rendercore.txt
n(0x00473f00, 'renderer::Renderable::SetElementDrawDist')  # names/rendercore.txt
n(0x00473f50, 'renderer::Renderable::GetElementDrawDist')  # names/rendercore.txt
n(0x00473fc0, 'renderer::Renderable::GetElementDrawable')  # names/rendercore.txt
n(0x00473fe0, 'renderer::Renderable::GetNumElements')  # names/rendercore.txt
n(0x00474000, 'renderer::Renderable::CopyElements')  # names/rendercore.txt
n(0x004740c0, 'renderer::Renderable::Tick')  # notes/renderspine.md
n(0x004740f0, 'renderer::Renderable::Display')  # notes/renderspine.md
n(0x00474aa0, 'renderer::Renderable::~Renderable')  # names/rendercore.txt
n(0x00474ac0, 'renderer::Renderable::SetNumElements')  # names/rendercore.txt
n(0x00474ba0, 'renderer::Renderable::Renderable')  # names/rendercore.txt
n(0x00474cd0, 'renderer::ShadowRenderable::Update')  # names/renderable_classes.txt
n(0x00474cf0, 'renderer::ShadowRenderable::ShadowRenderable')  # names/renderable_classes.txt
n(0x00474ea0, 'renderer::ShadowRenderable::~ShadowRenderable')  # names/renderable_classes.txt
n(0x004751c0, 'renderer::ShadowRenderable::Display')  # names/renderable_classes.txt
n(0x004758e0, 'renderer::ShadowLoader::ShadowLoader')  # names/renderable_classes.txt
n(0x00475930, 'renderer::ShadowLoader::LoadObject')  # names/renderable_classes.txt
n(0x00476090, 'renderer::SkidmarkPrimitive::Display')  # names/renderable_classes.txt
n(0x004760d0, 'renderer::SkidmarkPrimitive::GetTypeMask')  # names/renderable_classes.txt
n(0x004760f0, 'renderer::SkidmarkContainer::GetTypeMask')  # names/renderable_classes.txt
n(0x00476320, 'renderer::SkidmarkPrimitive::~SkidmarkPrimitive')  # names/renderable_classes.txt
n(0x004763f0, 'renderer::SkidmarkContainer::~SkidmarkContainer')  # names/renderable_classes.txt
n(0x00476410, 'renderer::SkidmarkRenderable::~SkidmarkRenderable')  # names/renderable_classes.txt
n(0x00476480, 'renderer::Skidmark::GetBoundingSphere')  # names/renderable_classes.txt
n(0x004764c0, 'renderer::Skidmark::Draw')  # names/renderable_classes.txt
n(0x00476a30, 'renderer::SkidmarkContainer::SkidmarkContainer')  # names/renderable_classes.txt
n(0x00476ad0, 'renderer::SkidmarkRenderable::SkidmarkRenderable')  # names/renderable_classes.txt
n(0x00476b80, 'renderer::SkidmarkRenderable::scalar_deleting_dtor')  # names/renderable_classes.txt
n(0x00476ba0, 'renderer::SkidmarkRenderable::Update')  # names/renderable_classes.txt
n(0x00477340, 'renderer::Skidmark::Skidmark')  # names/renderable_classes.txt
n(0x004773e0, 'renderer::DrawableContainer_DisplayImmediate')  # names/renderable_classes.txt
n(0x00477450, 'renderer::SkyRenderable::Display')  # names/renderable_classes.txt
n(0x00477470, 'renderer::SkyRenderable::SkyRenderable')  # names/renderable_classes.txt
n(0x004774e0, 'renderer::SkyRenderable::~SkyRenderable')  # names/renderable_classes.txt
n(0x00477500, 'renderer::SkyRenderable::Update')  # names/renderable_classes.txt
n(0x00477660, 'renderer::SkyLoader::SkyLoader')  # names/renderable_classes.txt
n(0x00477680, 'renderer::SkyLoader::LoadObject')  # names/renderable_classes.txt
n(0x00477a00, 'renderer::StatePropRenderable::InstantiateDrawable')  # names/renderable_classes.txt
n(0x00477b20, 'renderer::StatePropRenderable::StatePropRenderable_copy')  # names/renderable_classes.txt
n(0x00477d10, 'renderer::StatePropRenderable::~StatePropRenderable')  # names/renderable_classes.txt
n(0x00477e60, 'renderer::SFStatePropLoader::ClassifySize')  # names/renderable_classes.txt
n(0x00478070, 'renderer::StatePropRenderable::Update')  # names/renderable_classes.txt
n(0x00478160, 'renderer::SFStatePropLoader::SFStatePropLoader')  # names/renderable_classes.txt
n(0x00478180, 'renderer::SFStatePropLoader::LoadObject')  # names/renderable_classes.txt
n(0x00478430, 'renderer::TraceFireRenderable::Update')  # names/renderable_classes.txt
n(0x00478490, 'renderer::TraceFireRenderable::TraceFireRenderable')  # names/renderable_classes.txt
n(0x00478540, 'renderer::TraceFireRenderable::~TraceFireRenderable')  # names/renderable_classes.txt
n(0x00478560, 'renderer::TraceFireRenderable::RenderImmediate')  # names/renderable_classes.txt
n(0x00478b00, 'renderer::VehiclePrimitive::GetShader')  # names/renderable_classes.txt
n(0x00478b10, 'renderer::VehiclePrimitive::GetTypeMask')  # names/renderable_classes.txt
n(0x00478b20, 'renderer::VehicleContainer::GetTypeMask')  # names/renderable_classes.txt
n(0x00478b90, 'renderer::VehicleRenderable::Display')  # names/renderable_classes.txt
n(0x00478c50, 'renderer::VehiclePrimitive::~VehiclePrimitive')  # names/renderable_classes.txt
n(0x00478d00, 'renderer::VehiclePrimitive::Display')  # names/renderable_classes.txt
n(0x00478f00, 'renderer::VehiclePrimitive::CalcBounds')  # names/renderable_classes.txt
n(0x00478f30, 'renderer::VehicleContainer::~VehicleContainer')  # names/renderable_classes.txt
n(0x00478fb0, 'renderer::VehicleContainer::SetFading')  # names/renderable_classes.txt
n(0x00478fc0, 'renderer::VehicleContainer::IsFading')  # names/renderable_classes.txt
n(0x00478fd0, 'renderer::VehicleContainer::GetFadeAmount')  # names/renderable_classes.txt
n(0x00478fe0, 'renderer::VehicleContainer::Display')  # names/renderable_classes.txt
n(0x00479370, 'renderer::VehiclePrimitive::VehiclePrimitive')  # names/renderable_classes.txt
n(0x00479560, 'renderer::VehiclePrimitive::scalar_deleting_dtor')  # names/renderable_classes.txt
n(0x00479580, 'renderer::VehicleContainer::scalar_deleting_dtor')  # names/renderable_classes.txt
n(0x00479780, 'renderer::VehicleRenderable::~VehicleRenderable')  # names/renderable_classes.txt
n(0x00479a90, 'renderer::VehicleContainer::CalcBounds')  # names/renderable_classes.txt
n(0x00479cc0, 'renderer::VehicleRenderable::Update')  # names/renderable_classes.txt
n(0x00479cf0, 'renderer::VehicleLoader::VehicleLoader')  # names/renderable_classes.txt
n(0x00479e00, 'renderer::VehicleContainer::VehicleContainer')  # names/renderable_classes.txt
n(0x0047a5b0, 'renderer::VehicleLoader::LoadObject')  # names/renderable_classes.txt
n(0x0047aaa0, 'renderer::WakePrimitive::GetTypeMask')  # names/renderable_classes.txt
n(0x0047aac0, 'renderer::WakeContainer::GetTypeMask')  # names/renderable_classes.txt
n(0x0047ab90, 'renderer::WakePrimitive::Display')  # names/renderable_classes.txt
n(0x0047aed0, 'renderer::WakeContainer::~WakeContainer')  # names/renderable_classes.txt
n(0x0047af60, 'renderer::WakePrimitive::WakePrimitive')  # names/renderable_classes.txt
n(0x0047b040, 'renderer::WakePrimitive::~WakePrimitive')  # names/renderable_classes.txt
n(0x0047b450, 'renderer::WakeContainer::WakeContainer')  # names/renderable_classes.txt
n(0x0047b4e0, 'renderer::WakeRenderable::WakeRenderable')  # names/renderable_classes.txt
n(0x0047b5c0, 'renderer::WakeRenderable::~WakeRenderable')  # names/renderable_classes.txt
n(0x0047b660, 'renderer::WakeRenderable::Update')  # names/renderable_classes.txt
n(0x00488db0, 'ScriptObjectDataLoader::LoadLeafScriptObject')  # notes/instances.md
n(0x00488fb0, 'GameGroupDataLoader::LoadScriptObjectTree')  # notes/instances.md
n(0x004956e0, 'ScriptObject_CreateByClassName')  # notes/instances.md
n(0x004aee20, 'SInstanceSlot::ctor')  # notes/instances.md
n(0x004aef10, 'StatePropManager::SLocationData::GetScale')  # notes/instances.md
n(0x004af050, 'StatePropManager::SLocationData::ctor')  # notes/instances.md
n(0x004af0b0, 'StatePropManager::SLocationData::GetPosition')  # notes/instances.md
n(0x004af100, 'StatePropManager::SLocationData::SetRotation')  # notes/instances.md
n(0x004af280, 'StatePropManager::RegisterInstanceObject')  # notes/instances.md
n(0x004af300, 'StatePropManager::EraseLocations')  # notes/instances.md
n(0x004af620, 'StatePropManager::AddPreProcessedLocation')  # notes/instances.md
n(0x004afa00, 'StatePropManager::SetMaxCullingDistances')  # notes/instances.md
n(0x004afb50, 'StatePropManager::SLocationData::Set')  # notes/instances.md
n(0x004afee0, 'StatePropManager::QueueLocationForRenderableAdd')  # notes/instances.md
n(0x004aff50, 'StatePropManager::SetLocationEnabled')  # notes/instances.md
n(0x004b0000, 'StatePropManager::BuildInstanceMatrix')  # notes/instances.md
n(0x004b0130, 'StatePropManager::AddLocation')  # notes/instances.md
n(0x004b0250, 'StatePropManager::CreateInstanceRenderable')  # notes/instances.md
n(0x004b0530, 'StatePropManager::ProcessFadeCollidableList')  # notes/instances.md
n(0x004b0f10, 'StatePropManager::AddLocationToRenderable')  # notes/instances.md
n(0x004b1220, 'StatePropManager::ctor')  # notes/instances.md
n(0x004b1890, 'StatePropManager::RemoveActiveRenderablesByTemplate')  # notes/instances.md
n(0x004b1ac0, 'StatePropManager::RemoveLocationFromRenderable')  # notes/instances.md
n(0x004b1eb0, 'StatePropManager::UnregisterInstanceObject')  # notes/instances.md
n(0x004b2280, 'StatePropManager::InsertActiveRenderableSorted')  # notes/instances.md
n(0x004b2910, 'StatePropManager::CreateStatePropFromInstance')  # notes/instances.md
n(0x004b2c60, 'StatePropManager::InstanceSetStateByIndex')  # notes/instances.md
n(0x004b3080, 'StatePropManager::InstanceObjectInitialise')  # notes/instances.md
n(0x004b9440, 'StreamTriggerLoader::ctor')  # names/streaming.txt
n(0x004c1150, 'ChunkFile::GetPString')  # notes/instances.md
n(0x00559000, 'renderer::Renderable::GetDistanceRefPos')  # names/rendercore.txt
n(0x005e9150, 'InstanceObject::ctor')  # notes/instances.md
n(0x005e9250, 'InstanceObject::RegisterWithStatePropManager')  # notes/instances.md
n(0x005e9270, 'InstanceObject::SetStateByIndex')  # notes/instances.md
n(0x005e9410, 'InstanceObject::AddPreProcessedLocation')  # notes/instances.md
n(0x005e9490, 'InstanceObject::AddLocation')  # notes/instances.md
n(0x005e9880, 'InstanceObject::NotifyUnloadPackage')  # notes/instances.md
n(0x005e9b80, 'InstanceObject::dtor')  # notes/instances.md
n(0x00649b20, 'pure3d::pddiExtInstancing::MatrixPacketList::GetPacket')  # notes/instances.md
n(0x00649c10, 'pure3d::pddiExtInstancing::MatrixPacketList::Add')  # notes/instances.md
n(0x0064b8d0, 'pure3d::d3dContext::SetColourWrite')  # names/displaylist.txt
n(0x0064b990, 'pure3d::d3dContext::SetZWrite')  # names/displaylist.txt
n(0x0064b9f0, 'pure3d::d3dContext::EnableStencilBuffer')  # names/displaylist.txt
n(0x0064ba20, 'pure3d::d3dContext::SetStencilCompare')  # names/displaylist.txt
n(0x0064ba50, 'pure3d::d3dContext::SetStencilRef')  # names/displaylist.txt
n(0x0064bae0, 'pure3d::d3dContext::SetStencilOp')  # names/displaylist.txt
n(0x0064bb80, 'pure3d::d3dContext::EnableFog')  # names/displaylist.txt
n(0x0064be30, 'pure3d::d3dContext::GetExtension')  # names/displaylist.txt
n(0x0064d960, 'pure3d::pddiExtInstancing::WindyMatrixPacketList::ctor')  # notes/instances.md
n(0x0064ff10, 'pure3d::d3dContext::Clear')  # names/displaylist.txt
n(0x006503a0, 'pure3d::d3dContext::SetCullMode')  # names/displaylist.txt
n(0x00658e90, 'pure3d::pddiBaseContext::SetClearColour')  # names/displaylist.txt
n(0x00658ea0, 'pure3d::pddiBaseContext::GetClearColour')  # names/displaylist.txt
n(0x00658ec0, 'pure3d::pddiBaseContext::SetClearDepth')  # names/displaylist.txt
n(0x00658ed0, 'pure3d::pddiBaseContext::GetClearDepth')  # names/displaylist.txt
n(0x00658ee0, 'pure3d::pddiBaseContext::SetClearStencil')  # names/displaylist.txt
n(0x00658ef0, 'pure3d::pddiBaseContext::GetClearStencil')  # names/displaylist.txt
n(0x00658f00, 'pure3d::pddiBaseContext::IdentityMatrix')  # names/displaylist.txt
n(0x00658f30, 'pure3d::pddiBaseContext::LoadMatrix')  # names/displaylist.txt
n(0x00658f70, 'pure3d::pddiBaseContext::MultMatrix')  # names/displaylist.txt
n(0x00659d40, 'pure3d::pddiBaseContext::IsFogEnabled')  # names/displaylist.txt
n(0x00659fe0, 'pure3d::pddiBaseContext::PushMatrix')  # names/displaylist.txt
n(0x0065a010, 'pure3d::pddiBaseContext::PopMatrix')  # names/displaylist.txt
n(0x0065a030, 'pure3d::pddiBaseContext::GetMatrix')  # names/displaylist.txt
n(0x0065a050, 'pure3d::pddiBaseContext::PushIdentityMatrix')  # names/displaylist.txt
n(0x0065a0b0, 'pure3d::pddiBaseContext::PushLoadMatrix')  # names/displaylist.txt
n(0x0065a110, 'pure3d::pddiBaseContext::PushMultMatrix')  # names/displaylist.txt
n(0x00660a90, 'Matrix::SetRotation')  # notes/instances.md
n(0x006610f0, 'math::Matrix::TransformPoint')  # names/displaylist.txt
n(0x006834c0, 'pure3d::DrawableContainer::Display')  # names/renderable_classes.txt
n(0x006836e0, 'pure3d::DrawableContainer::SetElement')  # names/renderable_classes.txt
n(0x00683790, 'pure3d::DrawableContainer::CalcBounds')  # names/renderable_classes.txt
n(0x00685f70, 'pure3d::DrawablePrimitive::DrawablePrimitive')  # names/renderable_classes.txt
n(0x0068b850, 'pure3d::Camera::Camera')  # names/rendercore.txt
n(0x0068ee50, 'StatePropData::ReleaseCollisionObject')  # notes/statepropdata.md
n(0x0068f290, 'StatePropDataLoader::LoadObject')  # notes/statepropdata.md
n(0x0069e400, 'pure3d::Camera::TestSphereCameraSpace')  # names/rendercore.txt
n(0x0069e580, 'pure3d::Camera::SphereVisible')  # names/rendercore.txt
n(0x0069e690, 'pure3d::Camera::GetPosition')  # names/rendercore.txt
n(0x006a4c60, 'pure3d::PrimGroup::SetShader')  # names/renderable_classes.txt
n(0x006e8970, 'LinkedList::Insert')  # names/displaylist.txt
n(0x006e89e0, 'LinkedList::Remove')  # names/displaylist.txt
n(0x006e8a20, 'LinkedList::Sort')  # names/displaylist.txt
n(0x0073781c, 'renderer::RenderableHandle::vtable')  # names/renderable_classes.txt
n(0x00737824, 'renderer::SkidMarksHandle::vtable')  # names/renderable_classes.txt
n(0x007378a0, 'renderer::DecalsHandle::vtable')  # names/renderable_classes.txt
n(0x007378a8, 'renderer::TraceFireHandle::vtable')  # names/renderable_classes.txt
n(0x00737b3c, 'renderer::CharacterRenderable::vtable')  # names/renderable_classes.txt
n(0x00737b88, 'renderer::CharacterLoader::vtable')  # names/renderable_classes.txt
n(0x00737bb4, 'renderer::DecalPrimitive::vtable')  # names/renderable_classes.txt
n(0x00737bfc, 'renderer::DecalContainer::vtable')  # names/renderable_classes.txt
n(0x00737c78, 'renderer::DecalPrimitive::CDecalDrawable::vtable')  # names/renderable_classes.txt
n(0x00737c88, 'renderer::DecalPrimitive::CStaticDecalDrawable::vtable')  # names/renderable_classes.txt
n(0x00737c98, 'renderer::DecalPrimitive::COceanDecalDrawable::vtable')  # names/renderable_classes.txt
n(0x00737cac, 'renderer::DecalRenderable::vtable')  # names/renderable_classes.txt
n(0x00737cfc, 'renderer::InstanceContainer::vtable')  # names/renderable_classes.txt
n(0x00737d7c, 'renderer::InstancePrimitive::vtable')  # names/renderable_classes.txt
n(0x00737dc4, 'renderer::InstanceRenderable::vtable')  # names/renderable_classes.txt
n(0x00737eac, 'renderer::LightingRenderable::vtable')  # names/renderable_classes.txt
n(0x00737ef0, 'renderer::SFLightGroupLoader::vtable')  # names/renderable_classes.txt
n(0x00737f6c, 'renderer::MaskRenderable::vtable')  # names/renderable_classes.txt
n(0x00737fb4, 'renderer::NISRenderable::vtable')  # names/renderable_classes.txt
n(0x00737ffc, 'renderer::OceanContainer::vtable')  # names/renderable_classes.txt
n(0x0073807c, 'renderer::OceanPrimitive::vtable')  # names/renderable_classes.txt
n(0x007380c4, 'renderer::OceanRenderable::vtable')  # names/renderable_classes.txt
n(0x0073810c, 'renderer::ParticleEffectRenderable::vtable')  # names/renderable_classes.txt
n(0x00738154, 'renderer::PlugInRenderable::vtable')  # names/renderable_classes.txt
n(0x0073819c, 'renderer::PropRenderable::vtable')  # names/renderable_classes.txt
n(0x007381e4, 'renderer::WorldGeoRenderable::vtable')  # names/renderable_classes.txt
n(0x00738230, 'renderer::WorldGeoLoader::vtable')  # names/renderable_classes.txt
n(0x00738254, 'renderer::ZonePkgRenderable::vtable')  # names/renderable_classes.txt
n(0x00738298, 'renderer::ZonePkgLoader::vtable')  # names/renderable_classes.txt
n(0x0073833c, 'renderer::RainRenderable::vtable')  # names/renderable_classes.txt
n(0x0073838c, 'renderer::Renderable::vtable')  # names/renderable_classes.txt
n(0x007383d4, 'renderer::ShadowRenderable::vtable')  # names/renderable_classes.txt
n(0x0073841c, 'renderer::ShadowLoader::vtable')  # names/renderable_classes.txt
n(0x007384b8, 'renderer::Skidmark::vtable')  # names/renderable_classes.txt
n(0x007384cc, 'renderer::SkidmarkPrimitive::vtable')  # names/renderable_classes.txt
n(0x00738514, 'renderer::SkidmarkContainer::vtable')  # names/renderable_classes.txt
n(0x00738594, 'renderer::SkidmarkRenderable::vtable')  # names/renderable_classes.txt
n(0x007385e4, 'renderer::SkyRenderable::vtable')  # names/renderable_classes.txt
n(0x00738628, 'renderer::SkyLoader::vtable')  # names/renderable_classes.txt
n(0x0073864c, 'renderer::StatePropRenderable::vtable')  # names/renderable_classes.txt
n(0x00738690, 'renderer::SFStatePropLoader::vtable')  # names/renderable_classes.txt
n(0x007386b4, 'renderer::TraceFireRenderable::vtable')  # names/renderable_classes.txt
n(0x00738704, 'renderer::VehicleRenderable::vtable')  # names/renderable_classes.txt
n(0x0073874c, 'renderer::VehiclePrimitive::vtable')  # names/renderable_classes.txt
n(0x00738794, 'renderer::VehicleContainer::vtable')  # names/renderable_classes.txt
n(0x00738810, 'renderer::VehicleLoader::vtable')  # names/renderable_classes.txt
n(0x00738834, 'renderer::WakeContainer::vtable')  # names/renderable_classes.txt
n(0x007388b4, 'renderer::WakePrimitive::vtable')  # names/renderable_classes.txt
n(0x007388fc, 'renderer::WakeRenderable::vtable')  # names/renderable_classes.txt
n(0x0073be44, 'StreamTriggerLoader::vftable')  # names/streaming.txt
n(0x00769e14, 'pure3d::DrawableContainer::vtable')  # names/renderable_classes.txt
n(0x00769f24, 'pure3d::DrawablePrimitive::vtable')  # names/renderable_classes.txt
n(0x008108a0, 'renderer::g_displayList')  # names/rendercore.txt
n(0x00810cdc, 'occlude::g_statSpheresTested')  # names/rendercore.txt
n(0x00810ce0, 'occlude::g_statCulled')  # names/rendercore.txt
n(0x00810ce8, 'occlude::g_statOccluderTests')  # names/rendercore.txt
n(0x00810cf0, 'occlude::g_statPlaneTests')  # names/rendercore.txt
n(0x00810cfc, 'occlude::g_occlusionEnabled')  # names/rendercore.txt
n(0x00810d04, 'occlude::g_numOccluders')  # names/rendercore.txt
n(0x00810d10, 'occlude::g_occluders')  # names/rendercore.txt
n(0x008110a0, 'occlude::g_occluderNameCounter')  # names/rendercore.txt
n(0x008110a4, 'renderer::g_handlesCreated')  # names/rendercore.txt
n(0x008110a8, 'renderer::g_handlesDestroyed')  # names/rendercore.txt
n(0x008110ac, 'renderer::g_handlesLive')  # names/rendercore.txt
n(0x008110b0, 'renderer::g_colourEffectsEnabled')  # names/rendercore.txt
n(0x008110b4, 'renderer::g_destroyQueueCount')  # names/rendercore.txt
n(0x008110b8, 'renderer::g_destroyQueueCapacity')  # names/rendercore.txt
n(0x008110bc, 'renderer::g_destroyQueue')  # names/rendercore.txt
n(0x008111c8, 'renderer::g_renderAllocator')  # names/rendercore.txt
n(0x008111cc, 'renderer::gLightManager')  # names/rendercore.txt
n(0x008111d0, 'renderer::g_renderMgr')  # names/rendercore.txt
n(0x008111d4, 'renderer::g_defaultCamera')  # names/rendercore.txt
n(0x008111d8, 'renderer::g_renderCamera')  # names/rendercore.txt
n(0x008111dc, 'renderer::g_cullCamera')  # names/rendercore.txt
n(0x008111ec, 'renderer::g_renderFlowClient')  # names/rendercore.txt
n(0x008111f4, 'renderer::g_skidMarksHandleId')  # names/rendercore.txt
n(0x008111f8, 'renderer::g_decalsHandleId')  # names/rendercore.txt
n(0x008111fc, 'renderer::g_traceFireHandleId')  # names/rendercore.txt
n(0x00811200, 'renderer::g_buildingShadowHeap')  # names/rendercore.txt
n(0x00811204, 'renderer::g_particleEffectHeap')  # names/rendercore.txt
n(0x00811208, 'renderer::g_renderMgr2')  # names/rendercore.txt
n(0x008113f4, 'renderer::g_renderableUniqueId')  # names/rendercore.txt
n(0x008113f8, 'renderer::gSkidmarks')  # names/renderable_classes.txt
n(0x008114f0, 'renderer::g_smallStatePropSize')  # names/rendercore.txt
n(0x008114f4, 'renderer::g_mediumStatePropSize')  # names/rendercore.txt
n(0x00811504, 'renderer::g_vehicleBlockSize')  # names/rendercore.txt

# ---- struct layouts (apply by hand) ----
# [names/displaylist.txt] renderer::Display_List translation unit (PC retail, unpacked-image VAs)
# [names/displaylist.txt] Derived 2026-09-16, see re/notes/displaylist.md.  Lines "<addr> <name>".
# [names/displaylist.txt] A trailing " ?" marks a guess; everything else was read out of the disassembly.
# [names/displaylist.txt] 
# [names/displaylist.txt] ---------------------------------------------------------------------------
# [names/displaylist.txt] struct renderer::Display_List : pure3d::Entity     vtable 0x00737738
# [names/displaylist.txt] ctor 0x0045f110(int nodeCount), dtor 0x0045d9a0, size >= 0xcc
# [names/displaylist.txt] 0x00  void*                    vtable            (Entity base spans 0x00..0x2f)
# [names/displaylist.txt] 0x30  LinkedList*              lists             malloc(0x3f0) == 84 * 12
# [names/displaylist.txt] 0x34  LinkedList*              listsEnd          lists + 0x3f0
# [names/displaylist.txt] 0x3c  u8                       listDirty[84]     0x3c..0x8f; set by AddContainerElement,
# [names/displaylist.txt] cleared by SortAllLists after sorting
# [names/displaylist.txt] 0x90  LinkedList               freeList          {head, tail, count}
# [names/displaylist.txt] 0x9c  Node*                    nodeStore         one flat array, nodeCount * 0x70
# [names/displaylist.txt] 0xa0  Node*                    nodeStoreEnd
# [names/displaylist.txt] 0xa4  u32                      pad?              ?
# [names/displaylist.txt] 0xa8  bool                     unknownA8         ctor: 0                                 ?
# [names/displaylist.txt] 0xa9  bool                     doPostProcess     ctor: 1; gates the ext(0x103) tail      ?
# [names/displaylist.txt] 0xaa  bool                     cameraInsideVolume  recomputed at the top of SortAllLists ?
# [names/displaylist.txt] 0xac  pure3d::ShadowGenerator  shadowGen         embedded, vtable 0x00737718
# [names/displaylist.txt] 0xc4  void*                    lightCache        0x20-byte obj + 0x60-byte member        ?
# [names/displaylist.txt] 0xc8  u32                      shadowVolumeColour  0xff191919, used by RenderShadowVolumes
# [names/displaylist.txt] 
# [names/displaylist.txt] ---------------------------------------------------------------------------
# [names/displaylist.txt] struct renderer::Display_List::Node                stride 0x70 (112 bytes)
# [names/displaylist.txt] 0x00  ListLink                 link              {next, prev}; in lists[id] or freeList
# [names/displaylist.txt] 0x08  math::Matrix             matrix            world matrix captured at submit time
# [names/displaylist.txt] 0x48  float                    sortKey           container->+0x3c, or 0.0f/0.5f/1.0f per layer
# [names/displaylist.txt] 0x4c  float                    sortKey2          view-space z, written by ComputeDepthKeys
# [names/displaylist.txt] 0x50  pure3d::PrimArrayEntry*  elem              &container->elements[idx]  (16-byte stride)
# [names/displaylist.txt] 0x54  pure3d::DrawableContainer* container
# [names/displaylist.txt] 0x58  pure3d::Shader*          shader            elem->prim->GetShader(); the batching key
# [names/displaylist.txt] 0x5c  renderer::DisplayListPrimitive* parent     0 == orphan, recycled by FreeOrphanNodes
# [names/displaylist.txt] 0x60  LinkedList*              myList            &lists[listID]
# [names/displaylist.txt] 0x64  ListLink                 linkParent        {next, prev}; in parent->children
# [names/displaylist.txt] 0x6c  Node*                    self              == this; lets linkParent walk back to the node
# [names/displaylist.txt] 
# [names/displaylist.txt] ---------------------------------------------------------------------------
# [names/displaylist.txt] struct renderer::DisplayListPrimitive : GameDrawableInfo   vtable 0x00737704, size 0x20
# [names/displaylist.txt] ctor 0x00458c60, dtor 0x00458cc0
# [names/displaylist.txt] 0x00  void*                    vtable            {AddRef, Release, GetRef, dtor}
# [names/displaylist.txt] 0x04  u32                      unknown04         zeroed by ctor, NOT copied by the copy ctor ?
# [names/displaylist.txt] 0x08  renderer::Renderable*    owner             copied by operator=; read via node->parent
# [names/displaylist.txt] 0x0c  pure3d::DrawableHierarchy* drawable        ref-counted
# [names/displaylist.txt] 0x10  LinkedList               children          of Node::linkParent
# [names/displaylist.txt] 0x1c  u8                       flags             1 = visible, 2 = inList, 4 = flag4
# [names/displaylist.txt] 
# [names/displaylist.txt] ---------------------------------------------------------------------------
# [names/displaylist.txt] struct LinkedList  (0x006e89e0 Remove / 0x006e8970 Insert / 0x006e8a20 Sort)
# [names/displaylist.txt] 0x00  void*  head
# [names/displaylist.txt] 0x04  void*  tail
# [names/displaylist.txt] 0x08  int    count
# [names/displaylist.txt] links are {next at +0, prev at +4}; Insert pushes at the HEAD
# [names/displaylist.txt] 
# [names/displaylist.txt] ---------------------------------------------------------------------------
# [names/displaylist.txt] NOTE: pddiRenderContext (== the "matrix stack" at g[0x00831688], a wrapper whose +0 is the
# [names/displaylist.txt] context) matrix slots, correcting notes/renderspine.md:
# [names/displaylist.txt] +0x3c IdentityMatrix  +0x40 LoadMatrix  +0x44 PushMatrix  +0x48 PopMatrix
# [names/displaylist.txt] +0x4c MultMatrix (NOT Load)  +0x50 GetMatrix
# [names/displaylist.txt] +0x5c PushIdentityMatrix  +0x60 PushLoadMatrix  +0x64 PushMultMatrix
# [names/displaylist.txt] and state slots:
# [names/displaylist.txt] +0x18 SetClearColour  +0x30 Clear  +0xf8 SetCullMode  +0x100 SetColourWrite(r,g,b,a)
# [names/displaylist.txt] +0x108 EnableZBuffer  +0x118 SetZWrite  +0x120 EnableStencilBuffer  +0x128 SetStencilCompare
# [names/displaylist.txt] +0x130 SetStencilRef  +0x148 SetStencilOp  +0x158 EnableFog  +0x15c IsFogEnabled
# [names/displaylist.txt] +0x190 GetExtension  +0x1bc d3dContext::SetClearUsesQuad ?
# [names/displaylist.txt] ---------------------------------------------------------------------------
# [names/displaylist.txt] ---- Display_List lifetime -------------------------------------------------
# [names/displaylist.txt] ---- DisplayListPrimitive --------------------------------------------------
# [names/displaylist.txt] NOTE: notes/renderspine.md calls 0x458f00 "SetVisible". It is not: 0x458ec0 only sets the
# [names/displaylist.txt] visible bit and withdraws (callers Renderable::SetVisible 0x473c68, WorldGeoRenderable 0x471599),
# [names/displaylist.txt] 0x458f00 also SUBMITS (callers Renderable::Display 0x47458a/0x474605). This matches the split
# [names/displaylist.txt] aap already has in renderer/renderable.cpp.
# [names/displaylist.txt] ---- submission / node management -----------------------------------------
# [names/displaylist.txt] ---- culling helpers -------------------------------------------------------
# [names/displaylist.txt] ---- shader predicates -----------------------------------------------------
# [names/displaylist.txt] ---- sorting ---------------------------------------------------------------
# [names/displaylist.txt] ---- the frame ------------------------------------------------------------
# [names/displaylist.txt] ---- per-list renderers (lists they walk in the name) ----------------------
# [names/displaylist.txt] ---- outside the TU, but named here because this TU is the only caller -----
# [names/displaylist.txt] 00461ac0 renderer::View_GetRenderingCamera   -- named in names/rendercore.txt; g[0x8111d8],
# [names/displaylist.txt] the camera SortAllLists and RenderCameraLocked76 use (NOT 0x461ad0, the cull camera)
# [names/renderable_classes.txt] renderer:: renderable / container / primitive / handle classes  (PC retail)
# [names/renderable_classes.txt] Companion to re/notes/renderable_classes.md.  Format: "<hex addr> <name>".
# [names/renderable_classes.txt] Names for Renderable-base / RenderManager / Scene / handle plumbing live in
# [names/renderable_classes.txt] names/rendercore.txt (other agent); lines here that would collide are commented out.
# [names/renderable_classes.txt] ONE DELIBERATE DISAGREEMENT: 0x00466600 constructs a PropRenderable (ctor 0x004713e0
# [names/renderable_classes.txt] writes vtable 0x0073819c), not a PlugInRenderable -- 0x00464f00 is the PlugIn one.
# [names/renderable_classes.txt] Names without a trailing " ?" are verified from disassembly or from MSVC RTTI
# [names/renderable_classes.txt] (??_R4<Class>@renderer@@6B@ immediately preceding every vtable).
# [names/renderable_classes.txt] Names ending in " ?" are guesses.
# [names/renderable_classes.txt] '#' lines carry struct layouts as: offset type name
# [names/renderable_classes.txt] ---------------------------------------------------------------- base
# [names/renderable_classes.txt] (see names/rendercore.txt) 00473f50 renderer::Renderable::SetElementDrawable ?
# [names/renderable_classes.txt] (see names/rendercore.txt) 00473fc0 renderer::Renderable::GetElementDrawable
# [names/renderable_classes.txt] (see names/rendercore.txt) 00473aa0 renderer::Renderable::SetFadeTime
# [names/renderable_classes.txt] (see names/rendercore.txt) 00438400 renderer::Renderable::SetName_stub
# [names/renderable_classes.txt] (see names/rendercore.txt) 004747f0 renderer::Renderable::Renderable_copy ?
# [names/renderable_classes.txt] (see names/rendercore.txt) 00473cc0 renderer::Renderable::RefreshDrawable ?
# [names/renderable_classes.txt] 
# [names/renderable_classes.txt] renderer::Renderable : pure3d::Entity           size 0x84
# [names/renderable_classes.txt] 0x00 void*                 vtable
# [names/renderable_classes.txt] 0x04 i32                   refcount
# [names/renderable_classes.txt] 0x08 u32                   uid
# [names/renderable_classes.txt] 0x14 Matrix                matrix
# [names/renderable_classes.txt] 0x54 i32                   typeMask
# [names/renderable_classes.txt] 0x58 DisplayListElement*   elements_begin
# [names/renderable_classes.txt] 0x5c DisplayListElement*   elements_end
# [names/renderable_classes.txt] 0x60 DisplayListElement*   elements_cap
# [names/renderable_classes.txt] 0x64 u32                   uniqueId          (global counter 0x008113f4)
# [names/renderable_classes.txt] 0x68 float                 fadeTimeScale     (SetFadeTime; rate = 1000/x per second)
# [names/renderable_classes.txt] 0x6c float                 fade
# [names/renderable_classes.txt] 0x70 float                 fade2
# [names/renderable_classes.txt] 0x74 float                 fadeTarget
# [names/renderable_classes.txt] 0x78 float                 timeSinceDrawn
# [names/renderable_classes.txt] 0x7c i32                   sceneId           (Scene::AddRenderable writes Scene+0x14; ctor default 5)
# [names/renderable_classes.txt] 0x80 u8                    flags80           0x01 doDistanceTest  0x02 doFade  0x04 fadeDirection
# [names/renderable_classes.txt] 0x08 hasHandle       0x10 isVisible
# [names/renderable_classes.txt] 0x20 statePropFitsInPool
# [names/renderable_classes.txt] 0x40 useLastElementMaxDist
# [names/renderable_classes.txt] 0x80 useBoxBoundsFromPose
# [names/renderable_classes.txt] 0x81 u8                    flags81           0x02 isMatrixDirty
# [names/renderable_classes.txt] 
# [names/renderable_classes.txt] renderer::Renderable vtable slots
# [names/renderable_classes.txt] 0 AddRef  1 Release  2 GetRef  3 ~Renderable  4 Entity::vslot4 ?  5 Entity::Clone
# [names/renderable_classes.txt] 6 SetName(stub)  7 unknown ?  8 SetVisible  9 Update(TimeInfo*)  10 Display
# [names/renderable_classes.txt] 11 RenderImmediate  12 SetMatrix  13 GetPosition  14 Hide  15 GetDistanceRefPos
# [names/renderable_classes.txt] ---------------------------------------------------------------- scenes / manager (reference only)
# [names/renderable_classes.txt] (see names/rendercore.txt) 004675b0 renderer::RenderManager::GetLock
# [names/renderable_classes.txt] 
# [names/renderable_classes.txt] renderer::RenderManager
# [names/renderable_classes.txt] 0x04 Scene**       scenes            (pointer to an array of 4)
# [names/renderable_classes.txt] 0x10 Canvas*       canvas
# [names/renderable_classes.txt] 0x18 bool          initialised
# [names/renderable_classes.txt] 0x1c <interior/stateprop manager>     (ctor 0x0046bd80, size 0xc44, Update 0x0046c1d0)
# [names/renderable_classes.txt] 0x20 <decal/system object>            (ctor 0x00457800, size 0x58,  Update 0x00457fa0)
# [names/renderable_classes.txt] 0x24 <extra RenderImmediate pass>
# [names/renderable_classes.txt] 0x30 DecalRenderable*
# [names/renderable_classes.txt] 0x34 SkidmarkRenderable*
# [names/renderable_classes.txt] 0x38 TraceFireRenderable*
# [names/renderable_classes.txt] 0x3c Renderable*   playerRef
# [names/renderable_classes.txt] renderer::Scene       size 0x1c   (GamePlayScene 0x24)
# [names/renderable_classes.txt] 0x04 Renderable**  begin    0x08 end
# [names/renderable_classes.txt] 0x10 bool          enabled
# [names/renderable_classes.txt] 0x14 i32           sceneId
# [names/renderable_classes.txt] 0x18 u32           typeMaskFilter    (0xffffffff for all four)
# [names/renderable_classes.txt] 0x20 Display_List* displayList       (GamePlayScene only)
# [names/renderable_classes.txt] ---------------------------------------------------------------- WorldGeoRenderable
# [names/renderable_classes.txt] (layout: see notes/renderables.md section 4)
# [names/renderable_classes.txt] ---------------------------------------------------------------- ZonePkgRenderable
# [names/renderable_classes.txt] renderer::ZonePkgRenderable : Renderable   size 0x90  typeMask 0x8000
# [names/renderable_classes.txt] 0x84 WorldGeoRenderable**  worldGeos_begin
# [names/renderable_classes.txt] 0x88 WorldGeoRenderable**  worldGeos_end
# [names/renderable_classes.txt] 0x8c WorldGeoRenderable**  worldGeos_cap
# [names/renderable_classes.txt] ---------------------------------------------------------------- PropRenderable
# [names/renderable_classes.txt] renderer::PropRenderable : Renderable      size 0x84 (no own fields)  typeMask 8
# [names/renderable_classes.txt] ctor(DrawableHierarchy* d, float min, float max, float fade)
# [names/renderable_classes.txt] ---------------------------------------------------------------- StatePropRenderable
# [names/renderable_classes.txt] (layout: see notes/renderables.md section 2)
# [names/renderable_classes.txt] ---------------------------------------------------------------- InstanceRenderable family
# [names/renderable_classes.txt] (see names/rendercore.txt) 00467060 renderer::InstanceRenderable_CreateInstance
# [names/renderable_classes.txt] (see names/rendercore.txt) 00463f80 renderer::InstanceRenderable_SetCullDistance
# [names/renderable_classes.txt] renderer::InstanceRenderable : Renderable  size 0x88  typeMask 0x200
# [names/renderable_classes.txt] 0x84 InstanceContainer*  container
# [names/renderable_classes.txt] renderer::InstanceContainer : DrawableContainer   size 0x50
# [names/renderable_classes.txt] renderer::InstancePrimitive : DrawablePrimitive   size 0x7c  (layer 40/41/42)
# [names/renderable_classes.txt] 0x0c i32     layer
# [names/renderable_classes.txt] 0x38 Geometry* instanceShape
# [names/renderable_classes.txt] 0x3c Geometry* lodShape
# [names/renderable_classes.txt] 0x40 Geometry* lodShape2      (always 0 on PC)
# [names/renderable_classes.txt] 0x44 float     lodScale = 10.0
# [names/renderable_classes.txt] 0x48 float     lastFarBand
# [names/renderable_classes.txt] 0x4c float     swayAmount
# [names/renderable_classes.txt] 0x54 float     time           (written by InstanceRenderable::Update from TimeInfo+0x08)
# [names/renderable_classes.txt] 0x58 Vector    bboxMin   0x64 Vector bboxMax
# [names/renderable_classes.txt] 0x70 i32       bucket
# [names/renderable_classes.txt] 0x74 u8        flags (|=6)
# [names/renderable_classes.txt] 0x78 WindyMatrixPacketList*
# [names/renderable_classes.txt] ---------------------------------------------------------------- CharacterRenderable
# [names/renderable_classes.txt] renderer::CharacterRenderable : Renderable  size 0xbc  typeMask 0x20
# [names/renderable_classes.txt] 0x84 DrawableHierarchy* drawable
# [names/renderable_classes.txt] 0x88 pure3d::Shader*    shaders[8]     (0x88..0xa4)
# [names/renderable_classes.txt] 0xa8 void*              ?
# [names/renderable_classes.txt] 0xac u8 ?   0xad u8 ?
# [names/renderable_classes.txt] 0xb0 Vector             position       (returned by GetPosition)
# [names/renderable_classes.txt] ---------------------------------------------------------------- VehicleRenderable family
# [names/renderable_classes.txt] renderer::VehicleRenderable : Renderable   size 0xc0  typeMask 0x4000
# [names/renderable_classes.txt] 0x84 pure3d::Shader*     shaders[8]    (0x84..0xa0)
# [names/renderable_classes.txt] 0xa4 i32                 numShaders
# [names/renderable_classes.txt] 0xb0 CompositeDrawable*  composite     ? (on the loaded template)
# [names/renderable_classes.txt] 0xb4 CompositeDrawable*  lodComposite  ?
# [names/renderable_classes.txt] 0xb8 VehicleContainer*   container     ? (element 0 of the 2-element LOD chain)
# [names/renderable_classes.txt] 0xbc VehicleContainer*   lodContainer  ?
# [names/renderable_classes.txt] the clone (0x0047a180) builds TWO VehicleContainers and two DisplayListElements, so a
# [names/renderable_classes.txt] vehicle is a 2-element LOD chain and uses Renderable flags80 bit6 (useLastElementMaxDist)
# [names/renderable_classes.txt] renderer::VehicleContainer : DrawableContainer   size 0xd8
# [names/renderable_classes.txt] 0x3c float               sortKey       (world position, written every frame by Display)
# [names/renderable_classes.txt] 0x44/0x48 elements       (one VehiclePrimitive per part)
# [names/renderable_classes.txt] 0x50 <part table>        (init 0x00465050)
# [names/renderable_classes.txt] 0xc0 pure3d::Pose*       pose          private Pose::Copy of the composite's pose
# [names/renderable_classes.txt] 0xc4 pure3d::CompositeDrawable* source
# [names/renderable_classes.txt] 0xcc bool                isFading
# [names/renderable_classes.txt] 0xd0 float               fadeAmount
# [names/renderable_classes.txt] renderer::VehiclePrimitive : DrawablePrimitive
# [names/renderable_classes.txt] 0x0c i32     layer        (inherited from the source prim, or 32 when flags50 & 2)
# [names/renderable_classes.txt] 0x38 void*   parts        (n * 0x10)
# [names/renderable_classes.txt] 0x3c i32     numParts
# [names/renderable_classes.txt] 0x40 Sphere  bounds       (0x40..0x4c)
# [names/renderable_classes.txt] 0x50 u8      flags
# [names/renderable_classes.txt] 0x58 pure3d::Shader*  shaderB
# [names/renderable_classes.txt] 0x5c pure3d::Shader*  shader       (GetShader)
# [names/renderable_classes.txt] ---------------------------------------------------------------- SkyRenderable
# [names/renderable_classes.txt] (layout: see notes/renderables.md section 8)
# [names/renderable_classes.txt] ---------------------------------------------------------------- LightingRenderable
# [names/renderable_classes.txt] (layout: see notes/renderables.md section 5; Display is nullsub_2 0x005e1bb0)
# [names/renderable_classes.txt] ---------------------------------------------------------------- ShadowRenderable
# [names/renderable_classes.txt] (layout: see notes/renderables.md section 6)
# [names/renderable_classes.txt] ---------------------------------------------------------------- Decal family
# [names/renderable_classes.txt] ^ shared body `this->container->vslot10(0,0)`; used as vslot 11 by both
# [names/renderable_classes.txt] DecalRenderable and SkidmarkRenderable (MSVC ICF)
# [names/renderable_classes.txt] ^ shared body `elements[0]->vslot8()`; used as vslot 10 by both
# [names/renderable_classes.txt] DecalContainer and SkidmarkContainer (MSVC ICF)
# [names/renderable_classes.txt] 004760d0 (mask 0x01000000) is shared with renderer::SkidmarkPrimitive::GetTypeMask
# [names/renderable_classes.txt] (see names/rendercore.txt) 00464720 renderer::DecalsHandle::scalar_deleting_dtor
# [names/renderable_classes.txt] (see names/rendercore.txt) 008111f8 renderer::gNextDecalsHandleId
# [names/renderable_classes.txt] renderer::DecalRenderable : Renderable   size 0x88  typeMask 0x2000
# [names/renderable_classes.txt] 0x84 DecalContainer* container
# [names/renderable_classes.txt] renderer::DecalContainer : DrawableContainer   size 0x50   (sortKey +0x3c = 0.0)
# [names/renderable_classes.txt] renderer::DecalPrimitive : DrawablePrimitive   size 0x40
# [names/renderable_classes.txt] 0x0c i32    layer = 0    (unused: the container draws immediately)
# [names/renderable_classes.txt] 0x38 i32    maxDecals
# [names/renderable_classes.txt] 0x3c Decal* decals       (array of 0x24-byte records; +0x14 = 3, +0x00/+0x20 = 0)
# [names/renderable_classes.txt] renderer::DecalsHandle   size 0x14
# [names/renderable_classes.txt] 0x04 Renderable*     renderable (the singleton)   0x08 u32 uniqueId
# [names/renderable_classes.txt] 0x0c u32             handleId
# [names/renderable_classes.txt] 0x10 pure3d::Shader* shader
# [names/renderable_classes.txt] ---------------------------------------------------------------- Skidmark family
# [names/renderable_classes.txt] 0046d150 is shared: see renderer::Renderable::RenderImmediate_viaContainer
# [names/renderable_classes.txt] 004773e0 is shared: see renderer::DrawableContainer_DisplayImmediate
# [names/renderable_classes.txt] (see names/rendercore.txt) 004619f0 renderer::SkidMarksHandle::scalar_deleting_dtor
# [names/renderable_classes.txt] (see names/rendercore.txt) 008111f4 renderer::gNextSkidMarksHandleId
# [names/renderable_classes.txt] renderer::SkidmarkRenderable : Renderable  size 0x88  typeMask 0x100000
# [names/renderable_classes.txt] 0x84 SkidmarkContainer* container      (NOT bound as a DisplayListElement)
# [names/renderable_classes.txt] renderer::SkidmarkContainer : DrawableContainer  size 0x50  (sortKey +0x3c = 0.0)
# [names/renderable_classes.txt] renderer::SkidmarkPrimitive : DrawablePrimitive  size 0x3c  (layer 1, unused)
# [names/renderable_classes.txt] 0x38 bool  enabled = 1
# [names/renderable_classes.txt] renderer::Skidmark    size 0x684
# [names/renderable_classes.txt] 0x638 ?      0x63c Box bounds     0x654 u8      0x664 ?
# [names/renderable_classes.txt] 0x668 float = 1.0                 0x66c/0x66d u8
# [names/renderable_classes.txt] 0x67c float fadeDistance (5700.0 when released)   0x680 u8 active
# [names/renderable_classes.txt] renderer::gSkidmarks = Skidmark*[48] at 0x008113f8
# [names/renderable_classes.txt] ---------------------------------------------------------------- TraceFire
# [names/renderable_classes.txt] (see names/rendercore.txt) 00464840 renderer::TraceFireHandle::scalar_deleting_dtor
# [names/renderable_classes.txt] renderer::TraceFireRenderable : Renderable   size 0x8c  typeMask 2
# [names/renderable_classes.txt] 0x84 Tracer* tracers    (count * 0x4c bytes)
# [names/renderable_classes.txt] 0x88 i32     count
# [names/renderable_classes.txt] renderer::TraceFireHandle   size 0x14
# [names/renderable_classes.txt] 0x04 Renderable* renderable  0x08 uniqueId  0x0c handleId
# [names/renderable_classes.txt] 0x10 pure3d::CompositeDrawable* mesh
# [names/renderable_classes.txt] ---------------------------------------------------------------- Ocean family
# [names/renderable_classes.txt] renderer::OceanRenderable : Renderable   size 0x88  typeMask 0x40   (flags80 &= ~3)
# [names/renderable_classes.txt] 0x84 OceanContainer* container
# [names/renderable_classes.txt] renderer::OceanContainer : DrawableContainer  size 0x50  (sortKey +0x3c = 0.5f)
# [names/renderable_classes.txt] renderer::OceanPrimitive : DrawablePrimitive  size 0x48
# [names/renderable_classes.txt] 0x0c i32   layer = 27
# [names/renderable_classes.txt] 0x28 Sphere bounds  (re-centred on the camera each CalcBounds, radius 100000)
# [names/renderable_classes.txt] 0x38 pure3d ocean renderer object (ctor 0x00689af0, draw 0x00689aa0)
# [names/renderable_classes.txt] 0x3c/0x40/0x44  the three AddRef'd ctor arguments
# [names/renderable_classes.txt] ---------------------------------------------------------------- Wake family
# [names/renderable_classes.txt] renderer::WakeRenderable : Renderable   size 0x88  typeMask 0x80  (flags80 &= ~1)
# [names/renderable_classes.txt] 0x84 WakeContainer* container ; drawDist {0, 1000, 100}
# [names/renderable_classes.txt] renderer::WakeContainer : DrawableContainer  size 0x50  (sortKey +0x3c = 0.89f)
# [names/renderable_classes.txt] renderer::WakePrimitive : DrawablePrimitive  size 0xe94
# [names/renderable_classes.txt] 0x0c   i32    layer = 30
# [names/renderable_classes.txt] 0x4c   segment[40] of 0x1c bytes
# [names/renderable_classes.txt] 0x498  float  posA[...]     0x678 float posB[...]    0x8d0 <per-segment 8-byte>
# [names/renderable_classes.txt] 0x858  u8     alpha[...]
# [names/renderable_classes.txt] 0xe64  pure3d::Shader* shader
# [names/renderable_classes.txt] 0xe84  float = 2.0   0xe88 float = 3.0   0xe8c ?   0xe90 u8 flags
# [names/renderable_classes.txt] ---------------------------------------------------------------- RainRenderable
# [names/renderable_classes.txt] renderer::RainRenderable : Renderable   size 0x454  typeMask 0x800
# [names/renderable_classes.txt] 0xdc..0xe0 bools    0xe4 float = 0.2    0xe8 ?    0xec bool    0xf0 ?
# [names/renderable_classes.txt] 0x104 i32 = 3       0x108 drawable      0x150 ?
# [names/renderable_classes.txt] 0x3ac/0x3b0 ?       0x3b4 float = 1.0   0x3bc ?   0x3c4 i32 = -1   0x450 bool
# [names/renderable_classes.txt] ---------------------------------------------------------------- MaskRenderable
# [names/renderable_classes.txt] renderer::MaskRenderable : Renderable   size 0x84 (no own fields)  typeMask 0x1000
# [names/renderable_classes.txt] ctor(pure3d::Geometry* mesh, const char* name): every PrimGroup of mesh -> layer 36
# [names/renderable_classes.txt] ---------------------------------------------------------------- ParticleEffectRenderable
# [names/renderable_classes.txt] renderer::ParticleEffectRenderable : Renderable  size 0xa8  typeMask 4  (Display = nullsub)
# [names/renderable_classes.txt] 0x84 pure3d::ParticleSystem* system
# [names/renderable_classes.txt] 0x88 u32   emitterHandle
# [names/renderable_classes.txt] 0x8c bool  (CompositeDrawable::GetFlag4)
# [names/renderable_classes.txt] 0x90 float biasScale     0x94/0x98/0x9c floats
# [names/renderable_classes.txt] 0xa0 bool  hasBias       0xa4 DrawableHierarchy* drawable
# [names/renderable_classes.txt] ---------------------------------------------------------------- NISRenderable
# [names/renderable_classes.txt] renderer::NISRenderable : Renderable   size 0x90  typeMask 0x20000  (flags80 &= ~1)
# [names/renderable_classes.txt] 0x84 Vector position    (returned by GetPosition)
# [names/renderable_classes.txt] ---------------------------------------------------------------- PlugInRenderable
# [names/renderable_classes.txt] renderer::PlugInRenderable : Renderable   size 0x88  typeMask 0x40000
# [names/renderable_classes.txt] 0x84 RenderPlugIn* plugin       (vslot0 = render now)
# [names/renderable_classes.txt] vtable has 17 slots: slot 16 = Clone (the only renderable that adds a virtual)
# [names/renderable_classes.txt] ---------------------------------------------------------------- RenderableHandle
# [names/renderable_classes.txt] (see names/rendercore.txt) 00461860 renderer::RenderableHandle::RenderableHandle_default
# [names/renderable_classes.txt] (see names/rendercore.txt) 00461920 renderer::RenderableHandle::scalar_deleting_dtor
# [names/renderable_classes.txt] (see names/rendercore.txt) 004618d0 renderer::RenderableHandle::~RenderableHandle
# [names/renderable_classes.txt] (see names/rendercore.txt) 008110a4 renderer::gHandlesCreated
# [names/renderable_classes.txt] (see names/rendercore.txt) 008110a8 renderer::gHandlesDestroyed
# [names/renderable_classes.txt] (see names/rendercore.txt) 008110ac renderer::gHandlesLive
# [names/renderable_classes.txt] renderer::RenderableHandle   size 12
# [names/renderable_classes.txt] 0x00 void*        vtable
# [names/renderable_classes.txt] 0x04 Renderable*  renderable   (AddRef'd; sets renderable->flags80 |= 0x08)
# [names/renderable_classes.txt] 0x08 u32          uniqueId     (= renderable->+0x64; -1 after destruction)
# [names/renderable_classes.txt] dtor calls renderable->Hide() (vslot 14)
# [names/renderable_classes.txt] ---------------------------------------------------------------- pure3d base classes touched here
# [names/renderable_classes.txt] pure3d::DrawablePrimitive
# [names/renderable_classes.txt] 0x0c i32     layer       (default from PrimGroup::SetShader: 31 / 1 / 0)
# [names/renderable_classes.txt] 0x28 Sphere  boundingSphere  (0x28..0x34)
# [names/renderable_classes.txt] pure3d::DrawableContainer
# [names/renderable_classes.txt] 0x3c float   sortKey
# [names/renderable_classes.txt] 0x44/0x48    element array (stride 0x10, element[0] = DrawablePrimitive*)
# [names/renderable_classes.txt] DrawableContainer vslots: 10 Display(Display_List*, DisplayListPrimitive*)
# [names/renderable_classes.txt] 14 CalcBounds  17 SetFading  18 SetFadeAmount
# [names/renderable_classes.txt] 19 IsFading    20 GetFadeAmount   25 GetTypeMask
# [names/renderable_classes.txt] DrawablePrimitive vslots: 7 GetTypeMask  8 Display()  9 GetShader  13 CalcBounds
# [names/renderable_classes.txt] ---------------------------------------------------------------- drawable type masks (vslot 7 / 25)
# [names/renderable_classes.txt] 0x00020000 OceanPrimitive      0x00040000 OceanContainer
# [names/renderable_classes.txt] 0x00080000 WakePrimitive       0x00100000 WakeContainer
# [names/renderable_classes.txt] 0x00200000 InstancePrimitive   0x00400000 DecalPrimitive
# [names/renderable_classes.txt] 0x00800000 VehiclePrimitive == InstanceContainer   (one ICF-folded function, 0x478b10)
# [names/renderable_classes.txt] 0x01000000 SkidmarkPrimitive == DecalContainer     (one ICF-folded function, 0x4760d0)
# [names/renderable_classes.txt] 0x02000000 VehicleContainer    0x04000000 SkidmarkContainer
# [names/rendercore.txt] renderer:: core — RenderManager / Scene / Canvas / RenderFlowClient / Renderable /
# [names/rendercore.txt] RenderableHandle / the flat facade / cameras / occluders / light manager.
# [names/rendercore.txt] PC retail, unpacked-image VAs.  See re/notes/rendercore.md.
# [names/rendercore.txt] Names ending in " ?" are guesses; everything else was read out of the disassembly.
# [names/rendercore.txt] Function names in the facade come from the leaked game source
# [names/rendercore.txt] (grep -rhoE 'renderer::[A-Za-z_]+' /u/aap/lib/pure3d/scarface_src).
# [names/rendercore.txt] Class names come from the retail MSVC RTTI records (??_R4<Class>@renderer@@6B@).
# [names/rendercore.txt] ============================================================ struct layouts
# [names/rendercore.txt] renderer::RenderManager     0x104 bytes, vtable 0x007379b8 (2 slots), ctor 0x467a00
# [names/rendercore.txt] 0x00  void**                 vtable
# [names/rendercore.txt] 0x04  renderer::Scene**      scenes            // 4 entries
# [names/rendercore.txt] 0x08  renderer::Scene**      scenesEnd
# [names/rendercore.txt] 0x0c  u32                    spare
# [names/rendercore.txt] 0x10  renderer::Canvas*      canvas
# [names/rendercore.txt] 0x14  renderer::Canvas*      canvas2
# [names/rendercore.txt] 0x18  bool                   initialised
# [names/rendercore.txt] 0x19  bool                   skyEnabled
# [names/rendercore.txt] 0x1a  bool                   flag1a ?
# [names/rendercore.txt] 0x1c  renderer::EnvManager*  env ?             // 0xc44 bytes, ctor 0x46bd80
# [names/rendercore.txt] 0x20  renderer::DecalSystem* decalSystem ?     // 0x58 bytes, ctor 0x457800
# [names/rendercore.txt] 0x24  void*                  indoorExtraPass ?
# [names/rendercore.txt] 0x28  renderer::Renderable*  sky
# [names/rendercore.txt] 0x2c  renderer::Renderable*  sky2
# [names/rendercore.txt] 0x30  renderer::DecalRenderable*     decals
# [names/rendercore.txt] 0x34  renderer::SkidmarkRenderable*  skidmarks
# [names/rendercore.txt] 0x38  renderer::TraceFireRenderable* tracers
# [names/rendercore.txt] 0x3c  renderer::Renderable*  mainCharacter
# [names/rendercore.txt] 0x40  bool                   smallRenderBuffer ?
# [names/rendercore.txt] 0x41  bool                   videoModeApplied ?
# [names/rendercore.txt] 0x44  u32                    unused
# [names/rendercore.txt] 0x48  HeapInfo               heaps[12]         // stride 0x10
# [names/rendercore.txt] renderer::RenderManager::HeapInfo   0x10 bytes
# [names/rendercore.txt] 0x00  core::MemoryAllocator  allocator
# [names/rendercore.txt] 0x04  Heap*                  heap              // GetHeap() returns this
# [names/rendercore.txt] 0x08  u32                    numItems
# [names/rendercore.txt] 0x0c  u32                    spare
# [names/rendercore.txt] heap ids: 0 Vehicle 1 SmallStateProp 2 MediumStateProp 3 (unused) 4 Instance
# [names/rendercore.txt] 5 ParticleEffect 6 BuildingShadow 7 Shadow 8 Decal 9 Wake
# [names/rendercore.txt] 10 RenderableHandle 11 Empty
# [names/rendercore.txt] renderer::Scene             0x1c bytes, vtable 0x00737a80, ctor 0x468ed0(index, capacity)
# [names/rendercore.txt] 0x00  void**                 vtable
# [names/rendercore.txt] 0x04  renderer::Renderable** slots
# [names/rendercore.txt] 0x08  renderer::Renderable** slotsEnd
# [names/rendercore.txt] 0x0c  u32                    spare
# [names/rendercore.txt] 0x10  bool                   enabled
# [names/rendercore.txt] 0x14  i32                    index             // copied into Renderable+0x7c
# [names/rendercore.txt] 0x18  u32                    typeMaskFilter
# [names/rendercore.txt] renderer::GamePlayScene : Scene  0x24 bytes, vtable 0x00737a9c, ctor 0x468f90(index, cap, dlNodes)
# [names/rendercore.txt] 0x1c  float                     sortBias ?     // -0.0f
# [names/rendercore.txt] 0x20  renderer::Display_List*   displayList    // also published to g_displayList 0x8108a0
# [names/rendercore.txt] renderer::Canvas            0x38 bytes, vtable 0x007376e8 (1 slot), ctor 0x458210
# [names/rendercore.txt] 0x00  void**                 vtable
# [names/rendercore.txt] 0x04  pure3d::View*          view              // 0x150 bytes, ctor 0x67e330
# [names/rendercore.txt] 0x08  pure3d::Camera*        camera
# [names/rendercore.txt] 0x0c  bool                   enabled
# [names/rendercore.txt] 0x10  u32                    backgroundColour  // 0xff191919
# [names/rendercore.txt] 0x14  float                  fogFadeTimeLeft
# [names/rendercore.txt] 0x18  u32                    fogColour         // 0xff808080
# [names/rendercore.txt] 0x1c  float                  fogStart          // 100.0f
# [names/rendercore.txt] 0x20  float                  fogEnd            // 1000.0f
# [names/rendercore.txt] 0x24  i32                    fogDensity        // 200
# [names/rendercore.txt] 0x28  u32                    fogColourTo
# [names/rendercore.txt] 0x2c  float                  fogStartTo
# [names/rendercore.txt] 0x30  float                  fogEndTo
# [names/rendercore.txt] 0x34  i32                    fogDensityTo
# [names/rendercore.txt] renderer::RenderFlowClient  vtable 0x0073782c, ctor 0x465520, dtor 0x464c80
# [names/rendercore.txt] 0x00  void**                 vtable            // slot 2 = OnFrame
# [names/rendercore.txt] renderer::Renderable : pure3d::Entity   0x84 base, vtable 0x0073838c (16 slots), ctor 0x474ba0
# [names/rendercore.txt] 0x00  void**                 vtable
# [names/rendercore.txt] 0x04  i32                    refCount
# [names/rendercore.txt] 0x08  u32                    entityField
# [names/rendercore.txt] 0x0c  u32                    zero
# [names/rendercore.txt] 0x10  renderer::Room*        room
# [names/rendercore.txt] 0x14  math::Matrix           matrix            // 0x40; row3 at +0x44 = position
# [names/rendercore.txt] 0x54  i32                    typeMask
# [names/rendercore.txt] 0x58  DisplayListElement*    elements
# [names/rendercore.txt] 0x5c  DisplayListElement*    elementsEnd       // stride 0x30
# [names/rendercore.txt] 0x60  u32                    capacity
# [names/rendercore.txt] 0x64  u32                    uniqueId          // generation counter for handles
# [names/rendercore.txt] 0x68  float                  fadeRate          // UpdateFade steps by 1000/fadeRate per second
# [names/rendercore.txt] 0x6c  float                  fade              // 0 = opaque, 1 = gone
# [names/rendercore.txt] 0x70  float                  fade2
# [names/rendercore.txt] 0x74  float                  fadeTarget
# [names/rendercore.txt] 0x78  float                  timeSinceDrawn
# [names/rendercore.txt] 0x7c  i32                    sceneIndex
# [names/rendercore.txt] 0x80  u8                     flags80
# [names/rendercore.txt] 0x01 doDistanceTest  0x02 doFade   0x04 fadeDirectionOut  0x08 hasHandle
# [names/rendercore.txt] 0x10 isVisible       0x20 statePropFitsInPool
# [names/rendercore.txt] 0x40 shareLastElementFarDist        0x80 useBoxBoundsFromPose
# [names/rendercore.txt] 0x81  u8                     flags81
# [names/rendercore.txt] 0x01 isInsideRoom    0x02 matrixDirty
# [names/rendercore.txt] renderer::DisplayListElement  0x30 bytes
# [names/rendercore.txt] 0x00  float                  drawDistMin
# [names/rendercore.txt] 0x04  float                  drawDistMax
# [names/rendercore.txt] 0x08  float                  drawDistFade
# [names/rendercore.txt] 0x0c  DisplayListPrimitive   prim              // 0x20
# [names/rendercore.txt] 0x2c  bool                   isFading
# [names/rendercore.txt] renderer::RenderableHandle   0x0c bytes, vtable 0x0073781c (1 slot)
# [names/rendercore.txt] 0x00  void**                 vtable
# [names/rendercore.txt] 0x04  renderer::Renderable*  renderable
# [names/rendercore.txt] 0x08  u32                    uid               // snapshot of renderable->uniqueId
# [names/rendercore.txt] renderer::SkidMarksHandle : RenderableHandle   vtable 0x00737824, ctor 0x461980
# [names/rendercore.txt] 0x0c  u32                    id                // g[0x8111f4]++
# [names/rendercore.txt] 0x10  <subobject>                              // ctor 0x476120, dtor 0x476230
# [names/rendercore.txt] renderer::DecalsHandle    : RenderableHandle   vtable 0x007378a0, ctor 0x464690  (id g[0x8111f8])
# [names/rendercore.txt] renderer::TraceFireHandle : RenderableHandle   vtable 0x007378a8, ctor 0x4647b0  (id g[0x8111fc])
# [names/rendercore.txt] occlude::Occluder : pure3d::Entity   0x70 bytes, vtable 0x007377c8
# [names/rendercore.txt] 0x0c  math::Vector           boundsMin
# [names/rendercore.txt] 0x18  math::Vector           boundsMax
# [names/rendercore.txt] 0x24  float                  yaw
# [names/rendercore.txt] 0x28  bool                   isBoxOccluder
# [names/rendercore.txt] 0x29  bool                   isTypeOne ?
# [names/rendercore.txt] 0x2c  math::Box              box
# [names/rendercore.txt] 0x68  bool                   flag68 ?
# [names/rendercore.txt] 0x6c  i32                    id                // -1
# [names/rendercore.txt] occlude::OccluderInstance   0x98 bytes, array at 0x00810d10, count g[0x00810d04]
# [names/rendercore.txt] 0x00  math::Plane            planes[9]
# [names/rendercore.txt] 0x90  u32                    numPlanes
# [names/rendercore.txt] 0x94  occlude::Occluder*     occluder
# [names/rendercore.txt] renderer::LightManager   0x70 bytes, singleton g[0x008111cc], ctor 0x460600
# [names/rendercore.txt] 0x28  renderer::Room**       rooms
# [names/rendercore.txt] 0x2c  renderer::Room**       roomsEnd
# [names/rendercore.txt] 0x38  TemplateLight**        lights            // 0x100 slots
# [names/rendercore.txt] 0x6c  renderer::Room*        defaultRoom
# [names/rendercore.txt] renderer::LightManager::TemplateLight
# [names/rendercore.txt] 0x00  math::Matrix           transform
# [names/rendercore.txt] 0x40  u32                    templateId
# [names/rendercore.txt] 0x44  bool                   flag
# [names/rendercore.txt] 0x45  bool                   inUse
# [names/rendercore.txt] ============================================================ globals
# [names/rendercore.txt] ============================================================ RenderManager
# [names/rendercore.txt] ============================================================ Scene / GamePlayScene
# [names/rendercore.txt] ============================================================ Canvas
# [names/rendercore.txt] ============================================================ RenderFlowClient / init
# [names/rendercore.txt] ============================================================ Renderable
# [names/rendercore.txt] Renderable vtable slots: 0 AddRef 1 Release 2 GetRef 3 dtor 4 Clone 5 EntityClone
# [names/rendercore.txt] 6 SetName 7 GetName 8 SetVisible 9 Update(pre-display) 10 Display 11 DisplayImmediate
# [names/rendercore.txt] 12 SetMatrix 13 GetPosition 14 Hide 15 GetDistanceRefPos
# [names/rendercore.txt] ============================================================ RenderableHandle
# [names/rendercore.txt] ============================================================ cameras / view facade
# [names/rendercore.txt] ============================================================ generic Renderable facade
# [names/rendercore.txt] ============================================================ per-class facade
# [names/rendercore.txt] ============================================================ creation facade
# [names/rendercore.txt] ============================================================ time of day / environment
# [names/rendercore.txt] ============================================================ occluders
# [names/rendercore.txt] ============================================================ light manager
# [names/rendercore.txt] ============================================================ pure3d camera (used for culling)
# [names/streaming.txt] streaming — StreamTriggerLoader (chunk 0x08800101 in art/levels/z04/streamgraph.p3d).
# [names/streaming.txt] PC retail, unpacked-image VAs.  See re/notes/streaming.md.
