#!/usr/bin/env python3
"""Merge address->name files into one IDAPython script (re/ida_names.py).

Sources:
  re/names/*.txt        lines "<hex addr> <name>[ ?]"  ('?' = guess, skipped unless --guesses)
                        lines starting with '#' are struct-layout comments, copied verbatim
  re/notes/*.md         markdown table rows "| 0x00abcdef | some::Name |" whose name cell is a
                        clean C++ identifier (free-text cells are ignored)
Conflicts (same address, different names) are reported and the names/ file wins over notes.
Usage: python3 re/mkidanames.py [--guesses] > re/ida_names.py
"""
import re, sys, glob, os
here = os.path.dirname(os.path.abspath(__file__))
guesses = '--guesses' in sys.argv
ident = re.compile(r'^~?[A-Za-z_][\w]*(::~?[A-Za-z_][\w]*)*$')
names = {}; src = {}; comments = []
def add(addr, name, where, guess=False):
    if guess and not guesses: return
    name = name.strip()
    if not ident.match(name): return
    if name in ('u8','u16','u32','i8','i16','i32','int','float','bool','char','void','Vector','Matrix','ptr','u64'): return
    if not (0x401000 <= addr < 0x9fc000): return   # only image addresses (skips typeMask/chunk-id tables)
    if addr in names and names[addr] != name:
        if src[addr].startswith('names/'):  # names/ files win
            print('# conflict %08x: %s (%s) vs %s (%s) -> keeping first' % (addr, names[addr], src[addr], name, where))
            return
        print('# conflict %08x: %s (%s) replaced by %s (%s)' % (addr, names[addr], src[addr], name, where))
    names[addr] = name; src[addr] = where
for f in sorted(glob.glob(os.path.join(here, 'names', '*.txt'))):
    w = 'names/' + os.path.basename(f)
    for l in open(f):
        l = l.rstrip('\n')
        if not l.strip(): continue
        if l.startswith('#'): comments.append((w, l)); continue
        m = re.match(r'^\s*(?:0x)?([0-9a-fA-F]{6,8})\s+(\S+)(\s+\?)?\s*$', l)
        if m: add(int(m.group(1), 16), m.group(2), w, guess=bool(m.group(3)))
for f in sorted(glob.glob(os.path.join(here, 'notes', '*.md'))):
    w = 'notes/' + os.path.basename(f)
    for l in open(f):
        m = re.match(r'^\|\s*`?(?:0x)?([0-9a-fA-F]{6,8})`?\s*\|\s*`?([^|`]+?)`?\s*\|', l)
        if m: add(int(m.group(1), 16), m.group(2), w)
print('# generated by re/mkidanames.py — %d names; run in IDA: File > Script file' % len(names))
print('import idc, idaapi')
print('def n(ea, name):')
print('    if not idc.set_name(ea, name, idc.SN_NOWARN | idc.SN_FORCE):')
print('        print("failed: %x %s" % (ea, name))')
for a in sorted(names):
    print('n(0x%08x, %r)  # %s' % (a, names[a], src[a]))
if comments:
    print('\n# ---- struct layouts (apply by hand) ----')
    for w, l in comments: print('# [%s] %s' % (w, l[1:].strip()))
